# Generated by Django 2.2.11 on 2020-04-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organizationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='types',
            field=models.ManyToManyField(blank=True, help_text='Points to type of organization.', related_name='organization_type', to='organization.OrganizationType'),
        ),
    ]
