# Generated by Django 2.2.11 on 2020-06-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_organizationmember_projectmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, help_text='Points to detailed description about the project', max_length=4800, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, help_text='Points to short description about the project', max_length=240, null=True, verbose_name='Short Description'),
        ),
    ]
