# Generated by Django 2.2.11 on 2020-06-04 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_auto_20200601_1155'),
        ('organization', '0014_auto_20200528_1703'),
    ]

    operations = [
    ]
