# Generated by Django 2.2.11 on 2020-05-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_auto_20200525_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectparents',
            options={'verbose_name_plural': 'Project Parents'},
        ),
        migrations.AlterField(
            model_name='projectparents',
            name='order',
            field=models.IntegerField(help_text='Order in which project should be listed', unique=True, verbose_name='Order'),
        ),
    ]
