# Generated by Django 2.2.11 on 2020-06-09 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_remove_organization_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='organization_image',
            new_name='image',
        ),
    ]
