# Generated by Django 2.2.11 on 2020-06-07 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_auto_20200607_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectparents',
            name='project',
            field=models.ForeignKey(help_text="Points to organizations's project", on_delete=django.db.models.deletion.CASCADE, related_name='project_parent', to='organization.Project', verbose_name='Project'),
        ),
    ]
