# Generated by Django 2.2.11 on 2020-06-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_merge_20200604_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='organization_image',
            new_name='image',
        ),
    ]
