# Generated by Django 2.2.11 on 2020-06-16 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0017_auto_20200616_1006"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcomment",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                help_text="Point to comments table",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_project_comment",
                to="organization.Comment",
                verbose_name="Comment",
            ),
        ),
    ]
