# Generated by Django 2.2.11 on 2020-06-16 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0018_projectcomment_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postcomment",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="projectcomment",
            name="comment",
        ),
    ]
