# Generated by Django 2.2.11 on 2020-06-17 07:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0020_auto_20200617_0755"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="organizationtagging",
            unique_together={("organization", "organization_tag")},
        ),
        migrations.AlterUniqueTogether(
            name="projecttagging",
            unique_together={("project", "project_tag")},
        ),
    ]
