# Generated by Django 2.2.11 on 2020-06-17 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0024_auto_20200617_1232"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-id"],
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.RemoveField(
            model_name="projectparents",
            name="order",
        ),
    ]
