# Generated by Django 2.2.11 on 2020-06-17 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0027_auto_20200617_1441"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="organization_image",
        ),
    ]
