# Generated by Django 2.2.13 on 2020-06-23 11:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0031_auto_20200623_1043"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationtagging",
            name="additional_info",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationtags",
            name="additional_info",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projecttags",
            name="additional_info",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
