# Generated by Django 2.2.13 on 2020-07-06 14:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0040_project_is_draft"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationtagging",
            name="additional_info",
        ),
        migrations.RemoveField(
            model_name="organizationtags",
            name="additional_info",
        ),
        migrations.RemoveField(
            model_name="projecttagging",
            name="additional_info",
        ),
        migrations.RemoveField(
            model_name="projecttags",
            name="additional_info",
        ),
    ]
