# Generated by Django 2.2.13 on 2020-07-06 22:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0042_organizationtags_additional_info"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organizationmember",
            options={
                "ordering": ["-id"],
                "verbose_name": "Organization Member",
                "verbose_name_plural": "Organization Members",
            },
        ),
    ]
