# Generated by Django 2.2.13 on 2020-07-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0045_auto_20200713_0935"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="url_slug",
            field=models.CharField(
                blank=True,
                help_text="Points to organization url slug",
                max_length=1024,
                null=True,
                unique=True,
                verbose_name="URL Slug",
            ),
        ),
    ]
