# Generated by Django 2.2.13 on 2020-07-15 11:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organization", "0046_auto_20200713_1109"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="organizationmember",
            unique_together={("user", "organization")},
        ),
        migrations.AlterUniqueTogether(
            name="projectmember",
            unique_together={("user", "project")},
        ),
    ]
