# Generated by Django 2.2.13 on 2020-07-26 05:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0050_projectfollower"),
        ("organization", "0050_auto_20200725_0507"),
    ]

    operations = []
