# Generated by Django 2.2.13 on 2020-08-19 11:44

from django.db import migrations, models
import organization.models.project


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0052_auto_20200803_2021"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projecttagging",
            options={
                "ordering": ["-order"],
                "verbose_name": "Project Tagging",
                "verbose_name_plural": "Project Taggings",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="thumbnail_image",
            field=models.ImageField(
                blank=True,
                help_text="Image to show on project card",
                null=True,
                upload_to=organization.models.project.project_image_path,
                verbose_name="Thumbnail image",
            ),
        ),
    ]
