# Generated by Django 2.2.13 on 2020-08-27 05:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0055_auto_20200824_1819"),
        ("organization", "0053_auto_20200822_2112"),
    ]

    operations = []
