# Generated by Django 2.2.13 on 2020-12-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0057_organization_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.CharField(blank=True, help_text="Latitude of project's location", max_length=512, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, help_text='Project location', max_length=2048, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.CharField(blank=True, help_text="Longitude of project's location", max_length=512, null=True, verbose_name='Longitude'),
        ),
    ]
