# Generated by Django 2.2.13 on 2021-01-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0057_organization_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether the user is still assigned to the project ', verbose_name='Active'),
        ),
    ]
