# Generated by Django 2.2.13 on 2020-12-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0058_auto_20201207_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='latitude',
            field=models.CharField(blank=True, help_text="Latitude of organization's location", max_length=512, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='organization',
            name='location',
            field=models.CharField(blank=True, help_text='Organization location', max_length=2048, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='organization',
            name='longitude',
            field=models.CharField(blank=True, help_text="Longitude of organization's location", max_length=512, null=True, verbose_name='Longitude'),
        ),
    ]
