# Generated by Django 2.2.13 on 2021-02-02 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0004_auto_20210127_1452"),
        ("organization", "0059_auto_20210121_0637"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Points to the organization's location",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_loc",
                to="location.Location",
                verbose_name="Location",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="loc",
            field=models.ForeignKey(
                blank=True,
                help_text="Points to the project's location",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_loc",
                to="location.Location",
                verbose_name="Location",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Project location",
                max_length=2048,
                null=True,
                verbose_name="Location",
            ),
        ),
    ]
