# Generated by Django 2.2.13 on 2021-01-15 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('organization', '0059_auto_20201207_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='project',
            name='longitude',
        ),
        migrations.AddField(
            model_name='project',
            name='loc',
            field=models.ForeignKey(blank=True, help_text="Points to the project's location", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_location', to='location.Location', verbose_name='Location'),
        ),
    ]
