# Generated by Django 2.2.13 on 2021-01-25 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20210125_0927'),
        ('organization', '0059_auto_20210121_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='loc',
            field=models.ForeignKey(blank=True, help_text="Points to the project's location", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_location', to='location.Location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, help_text='Project location', max_length=2048, null=True, verbose_name='Location'),
        ),
    ]
