# Generated by Django 2.2.13 on 2021-01-21 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('organization', '0059_auto_20210121_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='latitude',
            field=models.CharField(blank=True, help_text="Latitude of organization's location", max_length=512, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='organization',
            name='location',
            field=models.CharField(blank=True, help_text='Organization location', max_length=2048, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='organization',
            name='longitude',
            field=models.CharField(blank=True, help_text="Longitude of organization's location", max_length=512, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='project',
            name='loc',
            field=models.ForeignKey(blank=True, help_text="Points to the project's location", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_location', to='location.Location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, help_text='Project location', max_length=2048, null=True, verbose_name='Location'),
        ),
    ]
