# Generated by Django 2.2.13 on 2021-01-25 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0060_auto_20210125_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='loc',
            field=models.ForeignKey(blank=True, help_text="Points to the project's location", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_loc', to='location.Location', verbose_name='Location'),
        ),
    ]
