# Generated by Django 2.2.13 on 2021-02-12 10:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0060_auto_20210202_0522"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="location",
        ),
    ]
