# Generated by Django 2.2.13 on 2021-01-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0061_auto_20210125_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='location',
            field=models.CharField(blank=True, help_text='Organization location', max_length=2048, null=True, verbose_name='Location'),
        ),
    ]
