# Generated by Django 2.2.13 on 2021-03-08 08:17

from django.db import migrations, models
import organization.models.organization


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0062_auto_20210215_1030"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="thumbnail_image",
            field=models.ImageField(
                blank=True,
                help_text="Thumbnail image",
                null=True,
                upload_to=organization.models.organization.organization_image_path,
                verbose_name="Thumbnail Image",
            ),
        ),
    ]
