# Generated by Django 2.2.13 on 2021-01-28 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0062_organization_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='location',
            field=models.ForeignKey(blank=True, help_text="Points to the organization's location", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_loc', to='location.Location', verbose_name='Location'),
        ),
    ]
