# Generated by Django 2.2.18 on 2021-04-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0066_organizationtranslation"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationtranslation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Time when translation object was created",
                null=True,
                verbose_name="Created at",
            ),
        ),
        migrations.AddField(
            model_name="organizationtranslation",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Time when translation object was updated",
                null=True,
                verbose_name="Updated at",
            ),
        ),
        migrations.AddField(
            model_name="projecttranslation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Time when translation object was created",
                null=True,
                verbose_name="Created at",
            ),
        ),
        migrations.AddField(
            model_name="projecttranslation",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Time when translation object was updated",
                null=True,
                verbose_name="Updated at",
            ),
        ),
    ]
