# Generated by Django 2.2.13 on 2021-04-15 05:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0073_auto_20210414_0816"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttranslation",
            name="helpful_connections_translation",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=528),
                blank=True,
                help_text="Translation of project's connections",
                null=True,
                size=10,
                verbose_name="Helpful Connections translation",
            ),
        ),
    ]
