# Generated by Django 2.2.13 on 2021-04-27 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0076_auto_20210422_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='short_description',
            new_name='about',
        ),
    ]
