# Generated by Django 2.2.13 on 2021-04-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0080_auto_20210427_1036"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="short_description",
            field=models.TextField(
                blank=True,
                help_text="Points to short description about the project",
                max_length=280,
                null=True,
                verbose_name="Short Description",
            ),
        ),
    ]
