# Generated by Django 2.2.24 on 2021-11-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0087_auto_20211027_1052"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationtags",
            name="show_in_climatematch",
            field=models.BooleanField(
                default=False,
                help_text="Help display organizations and projects in climate match",
                verbose_name="Show in climatematch?",
            ),
        ),
    ]
