# Generated by Django 2.2.24 on 2021-11-17 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0087_auto_20211027_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsShared',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when the user shared the project', verbose_name='Created At')),
                ('project', models.ForeignKey(help_text='Points to a project', on_delete=django.db.models.deletion.CASCADE, related_name='project_shared', to='organization.Project', verbose_name='Project')),
                ('user', models.ForeignKey(default='non-logged-in user', help_text='Points to the user who shared the project', on_delete=django.db.models.deletion.CASCADE, related_name='sharing_user', to=settings.AUTH_USER_MODEL, verbose_name='Sharing User')),
            ],
            options={
                'verbose_name': 'Project Shared',
                'verbose_name_plural': 'Projects Shared',
                'ordering': ['-id'],
            },
        ),
    ]
