# Generated by Django 2.2.24 on 2021-11-26 14:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0088_organizationtags_show_in_climatematch"),
        ("organization", "0089_auto_20211122_1835"),
    ]

    operations = []
