# Generated by Django 2.2.24 on 2021-11-29 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0090_merge_20211126_1438"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProjectsShared",
        ),
    ]
