# Generated by Django 2.2.24 on 2021-12-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0090_merge_20211126_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event_date',
            field=models.DateField(blank=True, help_text='Date of the event the update is about', null=True, verbose_name='Date of event'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Dafault Title', help_text='Title of the post', max_length=100, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
