# Generated by Django 2.2.24 on 2022-01-01 22:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0091_delete_projectsshared"),
        ("organization", "0087_auto_20210725_2154"),
    ]

    operations = []
