# Generated by Django 2.2.24 on 2022-01-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0091_delete_projectsshared'),
        ('organization', '0091_auto_20211210_0652'),
    ]

    operations = [
    ]
