# Generated by Django 2.2.24 on 2022-01-01 22:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organization", "0092_merge_20220101_2230"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershiprequests",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="membershiprequests",
            name="message",
            field=models.TextField(
                blank=True,
                help_text="Message associated with the request",
                max_length=4096,
                null=True,
                verbose_name="Request Message",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="membershiprequests",
            unique_together={("user", "target_project")},
        ),
    ]
