# Generated by Django 2.2.24 on 2022-01-13 10:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climateconnect_api', '0077_merge_20211213_1307'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0092_merge_20220104_1711'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectLike',
            new_name='Like',
        ),
    ]
