# Generated by Django 2.2.24 on 2022-01-13 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0093_auto_20220113_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(blank=True, help_text='Points to a post', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_liked', to='organization.Post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Points to a project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_liked', to='organization.Project', verbose_name='Project'),
        ),
    ]
