# Generated by Django 2.2.24 on 2022-01-13 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0094_auto_20220113_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-id'], 'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
    ]
