# Generated by Django 2.2.28 on 2022-05-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0094_auto_20220401_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='hubs',
            field=models.ManyToManyField(blank=True, help_text='Sector Hubs that the organization is active in', related_name='organization_hubs', to='hubs.Hub', verbose_name='Hubs'),
        ),
    ]
