# Generated by Django 2.2.28 on 2022-06-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0094_auto_20220401_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event_date',
            field=models.DateField(blank=True, help_text='Date of the event the update is about', null=True, verbose_name='Date of event'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', help_text='Title of the post', max_length=100, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='{"blocks":[{"text":"REPLACE THIS STRING WITH YOUR TEXT","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{}}', help_text='Content of the post: To add a content text replace the marked string with your plain and unstyled text.', verbose_name='Content'),
        ),
    ]
