# Generated by Django 3.2.14 on 2022-07-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0095_auto_20220419_0744'),
        ('organization', '0095_auto_20220530_1356'),
    ]

    operations = [
    ]
