# Generated by Django 3.2.15 on 2022-10-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0097_auto_20220927_1237"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationtags",
            name="hide_get_involved",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether or not this type should hide the get involved field",
                verbose_name="Hide Get Involved field",
            ),
        ),
    ]
