# Generated by Django 3.2.14 on 2022-08-08 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0097_orgprojectpublished'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgprojectpublished',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiving_organization_follower', to='organization.organizationfollower', verbose_name='Organization Follower that will receive notification'),
        ),
    ]
