# Generated by Django 3.2.15 on 2022-11-15 07:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0098_orgprojectpublished"),
        ("organization", "0100_alter_organizationtranslation_get_involved_translation"),
    ]

    operations = []
