# Generated by Django 3.2.16 on 2023-04-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0102_auto_20230327_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttypes',
            name='help_text',
            field=models.TextField(help_text='Small helper text that is shown under the name in the shrae project interface', max_length=512, verbose_name='Helptext'),
        ),
        migrations.AlterField(
            model_name='projecttypes',
            name='help_text_de',
            field=models.TextField(help_text='Translation of help_text column', max_length=512, verbose_name='Helptext DE translation'),
        ),
        migrations.AlterField(
            model_name='projecttypes',
            name='name',
            field=models.CharField(help_text='Name of the project type', max_length=512, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='projecttypes',
            name='name_de_translation',
            field=models.CharField(help_text='Translation of name column', max_length=512, verbose_name='Name DE translation'),
        ),
        migrations.AlterField(
            model_name='projecttypes',
            name='type_id',
            field=models.IntegerField(choices=[('project', 'project'), ('idea', 'idea'), ('event', 'event')], default='project', help_text='Type of the status. Used as unique identifier', verbose_name='Status Type'),
        ),
    ]
