# Generated by Django 3.2.18 on 2023-07-24 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0102_auto_20230722_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_type',
        ),
        migrations.DeleteModel(
            name='ProjectTypes',
        ),
    ]
