# Generated by Django 3.2.23 on 2024-09-12 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0103_alter_projectmember_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiprequests',
            name='message',
        ),
    ]
