# Generated by Django 3.2.23 on 2024-10-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0019_remove_hub_filter_parent_tags'),
        ('organization', '0103_alter_projectmember_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hubs',
            field=models.ManyToManyField(blank=True, help_text='Hubs that the project is active in', related_name='project_hubs', to='hubs.Hub', verbose_name='Hubs'),
        ),
    ]
