# Generated by Django 3.2.18 on 2023-06-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0103_auto_20230410_0554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttypes',
            old_name='help_text_de',
            new_name='help_text_de_translation',
        ),
        migrations.AlterField(
            model_name='projecttypes',
            name='type_id',
            field=models.IntegerField(choices=[(0, 'project'), (1, 'idea'), (2, 'event')], default=0, help_text='Type of the status. Used as unique identifier', verbose_name='Status Type'),
        ),
    ]
