# Generated by Django 3.2.18 on 2023-07-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0103_auto_20230724_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('ID', 'Idea'), ('EV', 'Event'), ('PR', 'Project')], default='PR', max_length=2),
        ),
    ]
