# Generated by Django 3.2.23 on 2025-01-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0033_remove_hubtheme_background_paper'),
        ('organization', '0103_alter_projectmember_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='related_hubs',
            field=models.ManyToManyField(blank=True, related_name='projects_related_hubs', to='hubs.Hub'),
        ),
    ]
