# Generated by Django 3.2.18 on 2023-07-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0104_auto_20230609_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='additional_loc_info',
            field=models.CharField(blank=True, help_text='e.g. Room or other instructions to get to the location', max_length=256, null=True, verbose_name='Additional location info'),
        ),
    ]
