# Generated by Django 3.2.23 on 2025-05-07 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0105_organization_related_hubs_alter_organization_hubs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershiprequests',
            old_name='message',
            new_name='message_old',
        ),
    ]
