# Generated by Django 3.2.25 on 2025-03-07 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0105_organization_related_hubs_alter_organization_hubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(blank=True, help_text="Points to project's status", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_status', to='organization.projectstatus', verbose_name='Project Status'),
        ),
    ]
