# Generated by Django 3.2.25 on 2025-03-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0105_organization_related_hubs_alter_organization_hubs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
