# Generated by Django 3.2.25 on 2025-04-21 19:40

from django.db import migrations, models
import django.db.models.deletion

from organization.models import ProjectTagging, Project, ProjectSectorMapping, Sector

DEBUG_PREFIX = "T-SECTOR"


class Sector_Definition:
    def __init__(self, name, de_translated_name, key):
        self.name = name
        self.de_translated_name = de_translated_name
        self.key = key


SECTOR_DEFINITIONS = {
    x.key: x
    for x in [
        Sector_Definition(
            "Food",
            "Ernährung",
            "food",
        ),
        Sector_Definition(
            "Agri & Land use",
            "Landwirtschaft & Landnutzung",
            "agri",
        ),
        Sector_Definition(
            "Buildings",
            "Bauen und Wohnen",
            "buldings",
        ),
        Sector_Definition(
            "Energy",
            "Energiewende",
            "energy",
        ),
        Sector_Definition(
            "Policy & Governance",
            "Politik und Verwaltung",
            "policy",
        ),
        Sector_Definition(
            "Education, Social Action & Health",
            "Bildung, Soziale Aktion & Gesundheit",
            "education",
        ),
        Sector_Definition(
            "Mobility",
            "Mobilität",
            "mobility",
        ),
        Sector_Definition(
            "Industry & Building",
            "Industrie & Bauwesen",
            "industry",
        ),
        Sector_Definition(
            "Costal and Ocean sinks",
            "Küsten- und Ozeanspeicher",
            "costal",
        ),
        Sector_Definition(
            "Engineered sinks",
            "Technisch erzeugte Speicher",
            "engineered",
        ),
        Sector_Definition(
            "Research",
            "Wissenschaft",
            "research",
        ),
        Sector_Definition(
            "Climate change adaption",
            "Anpassung an den Klimawandel",
            "adaption",
        ),
        Sector_Definition(
            "Climate justice",
            "Klimagerechtigkeit",
            "justice",
        ),
    ]
}
DELETION_TOKEN = "DELETION_TOKEN"

MAPPING = {
    "Air": SECTOR_DEFINITIONS["industry"],
    "Construction": SECTOR_DEFINITIONS["industry"],
    "Buildings": SECTOR_DEFINITIONS["buldings"],
    "Climate change adaption": SECTOR_DEFINITIONS["adaption"],
    "Climate justice": SECTOR_DEFINITIONS["justice"],
    "Education & Social action": SECTOR_DEFINITIONS["education"],
    "Energy": SECTOR_DEFINITIONS["energy"],
    "Food": SECTOR_DEFINITIONS["food"],
    "funing": DELETION_TOKEN,
    "Geoengineering": SECTOR_DEFINITIONS["engineered"],
    "Land use": SECTOR_DEFINITIONS["agri"],
    "Policy & Governance": SECTOR_DEFINITIONS["policy"],
    "Product": DELETION_TOKEN,
    "Production, consumption and recycling": SECTOR_DEFINITIONS["industry"],
    "Research": SECTOR_DEFINITIONS["research"],
    "Mobility": SECTOR_DEFINITIONS["mobility"],
    "Water": DELETION_TOKEN,  # TODO
    "Reducing marine pollution": SECTOR_DEFINITIONS["costal"],
    "Fighting ocean acidification": SECTOR_DEFINITIONS["costal"],
    "Fighting overfishing": SECTOR_DEFINITIONS["costal"],
    "Protecting marine ecosystems": SECTOR_DEFINITIONS["costal"],
    "Improving water use efficiency": SECTOR_DEFINITIONS["industry"],
    "Water recycling": SECTOR_DEFINITIONS["industry"],
    "Event": DELETION_TOKEN,
}


def create_sectors(apps, schema_editor):
    Sector = apps.get_model("organization", "Sector")

    for sector in SECTOR_DEFINITIONS.values():
        Sector.objects.get_or_create(
            name=sector.name,
            key=sector.key,
            name_de_translation=sector.de_translated_name,
        )


def generate_sector_mappings_from_project_taggings(apps, schema_editor):
    # ProjectTagging = apps.get_model("organization", "ProjectTagging")
    # ProjectSectorMapping = apps.get_model("organization", "ProjectSectorMapping")
    # Sector = apps.get_model("organization", "Sector")

    added_mappings = 0
    deleted_mappings = 0
    missing_mappings = 0

    for tagging in ProjectTagging.objects.all():
        project = tagging.project
        if not project or not project.name.startswith(DEBUG_PREFIX):
            continue

        tag = tagging.project_tag

        sector_def = MAPPING.get(tag.name, None)

        # propagate sector mapping to the parent tag
        # if specification for current tag is not found
        if sector_def is None and tag.parent_tag is not None:
            parent_tag = tag.parent_tag
            sector_def = MAPPING.get(parent_tag.name, None)

        if sector_def is DELETION_TOKEN:
            print(
                f"[MIGRATION] [-]\tDELETION TOKEN found: '{tag.name}', will skip the mapping "
                + f"for [project]'{project.name}'--'{tag.name}[tag]'"
            )
            deleted_mappings += 1
            continue

        if sector_def is None:
            print(
                f"[MIGRATION] [!]\tNo mapping found for tag '{tag.name}', will skip the mapping "
                + f"for [project]'{project.name}'--'{tag.name}[tag]'"
            )
            missing_mappings += 1
            continue

        sector = Sector.objects.get(key=sector_def.key)
        ProjectSectorMapping.objects.get_or_create(
            project=project,
            sector=sector,
        )
        print(
            f"[MIGRATION] [+]\tCreated mapping for [project]'{project.name}' -- '{tag.name}'[tag] ==> '{sector_def.key}'[sector] "
        )
        added_mappings += 1

    print("" + "-" * 80)
    print(f"[MIGRATION] >> {added_mappings}\tadded mappings)")
    print(f"[MIGRATION] >> {deleted_mappings}\tdeleted mappings)")
    print(f"[MIGRATION] >> {missing_mappings}\tmissing mappings)")
    print()
    # Organization = apps.get_model("organization", "Organization")
    # OrganizationSectorMapping = apps.get_model(
    #     "organization", "OrganizationSectorMapping"
    # )
    # for organization in Organization.objects.all():
    #     for tag in organization.tags.all():
    #         if tag.name in MAPPING:
    #             sector = MAPPING[tag.name]
    #             if sector is not None:
    #                 OrganizationSectorMapping.objects.get_or_create(
    #                     organization=organization,
    #                     sector=sector,
    #                 )


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0105_organization_related_hubs_alter_organization_hubs"),
    ]

    operations = [
        ####################################################
        # auto generateed migration
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the sector",
                        max_length=256,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_de_translation",
                    models.CharField(
                        blank=True,
                        help_text="German traslation of the name column",
                        max_length=256,
                        null=True,
                        verbose_name="Name DE translation",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="unique search key of the sector. Example: `Student organization` becomes studentorganization",
                        max_length=256,
                        unique=True,
                        verbose_name="Key",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Time when sector was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Time when sector was updated",
                        verbose_name="Updated at",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sector",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectSectorMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Time when mapping was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Time when mapping was updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="The bigger the number, the more to the top this sector will be displayed",
                        verbose_name="Position of tag",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.project",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.sector",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Sector Mapping",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationSectorMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Time when mapping was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Time when mapping was updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="The bigger the number, the more to the top this sector will be displayed",
                        verbose_name="Position of tag",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.organization",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.sector",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Sector Mapping",
                "ordering": ["id"],
            },
        ),
        ####################################################
        # manual addition
        migrations.RunPython(
            create_sectors,
            reverse_code=migrations.RunPython.noop,
        ),
        # Link sectors to existing sector hubs (use key and url_slug)
        # migration for organizations: link to hub changes to link to hub.sector
        migrations.RunPython(
            generate_sector_mappings_from_project_taggings,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
