# Generated by Django 3.2.25 on 2025-03-14 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0106_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(blank=True, default=1, help_text="Points to project's status", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_status', to='organization.projectstatus', verbose_name='Project Status'),
        ),
    ]
