# Generated by Django 3.2.25 on 2025-03-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0106_remove_project_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectStatus',
        ),
    ]
