# Generated by Django 3.2.23 on 2025-05-07 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0018_manually_add_permission'),
        ('organization', '0106_rename_message_membershiprequests_message_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiprequests',
            name='message',
            field=models.ForeignKey(blank=True, help_text='Message associated with the request', null=True, on_delete=django.db.models.deletion.CASCADE, to='chat_messages.message', verbose_name='Request Message'),
        ),
    ]
