# Generated by Django 3.2.25 on 2025-05-19 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0108_sectors_images_and_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsectormapping',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_sector_mapping', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='organizationsectormapping',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_sector_mapping', to='organization.sector'),
        ),
        migrations.AlterField(
            model_name='projectsectormapping',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_sector_mapping', to='organization.project'),
        ),
        migrations.AlterField(
            model_name='projectsectormapping',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_sector_mapping', to='organization.sector'),
        ),
        migrations.AlterUniqueTogether(
            name='projectsectormapping',
            unique_together={('sector', 'project')},
        ),
    ]
