# Generated by Django 3.2.25 on 2025-07-09 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0109_auto_20250519_1951"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="organizationsectormapping",
            unique_together={("sector", "organization")},
        ),
    ]
