# Generated by Django 3.2.25 on 2025-07-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0110_alter_organizationsectormapping_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='key',
            field=models.CharField(help_text="unique search key of the sector. Example: 'Food & Agriculture' becomes foodagriculture", max_length=256, unique=True, verbose_name='Key'),
        ),
    ]
