# Generated by Django 3.2.25 on 2025-07-31 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0111_alter_sector_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='default_sector',
            field=models.BooleanField(default=True, help_text='If this sector is a default sector, it will be used if no specific sector is selected.', verbose_name='Default sector'),
        ),
        migrations.AddField(
            model_name='sector',
            name='relates_to_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hub_specific_sector', to='organization.sector'),
        ),
    ]
