# Generated by Django 3.2.25 on 2025-07-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0111_alter_sector_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(help_text="Name of the sector. It shall neither contain ',' nor '_' nor '&', as this can cause issues with the search functionality", max_length=256, verbose_name='Name'),
        ),
    ]
