# Generated by Django 3.2.25 on 2025-08-11 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0112_auto_20250806_1052'),
        ('organization', '0113_auto_20250807_0835'),
    ]

    operations = [
    ]
