# Generated by Django 3.2.25 on 2025-10-22 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0113_auto_20250807_0835"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.ForeignKey(
                blank=True,
                default=1,
                help_text="Points to project's status",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_status",
                to="organization.projectstatus",
                verbose_name="Project Status",
            ),
        ),
    ]
