# Generated by Django 3.2.25 on 2026-01-15 06:37

from django.db import migrations, models
import django.db.models.deletion


def populate_has_children(apps, schema_editor):
    """
    Populate has_children field based on existing child_projects relationships.

    This function runs after the fields are created to ensure any existing
    parent/child relationships (if they exist) have the correct has_children flag.
    Since this is a new feature, there should be no existing relationships,
    but this makes the migration safe and reusable.
    """
    Project = apps.get_model('organization', 'Project')
    db_alias = schema_editor.connection.alias

    # Find all projects with children and set has_children=True
    parent_ids = Project.objects.using(db_alias).filter(
        child_projects__isnull=False
    ).values_list('id', flat=True).distinct()

    if parent_ids:
        Project.objects.using(db_alias).filter(
            id__in=parent_ids
        ).update(has_children=True)


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0114_merge_0112_auto_20250806_1052_0113_auto_20250807_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='has_children',
            field=models.BooleanField(db_index=True, default=False, help_text='Denormalized flag indicating if this project has child projects. Kept in sync via signals.'),
        ),
        migrations.AddField(
            model_name='project',
            name='parent_project',
            field=models.ForeignKey(blank=True, help_text='Parent project for multi-event structures (e.g., festival with sub-events)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_projects', to='organization.project'),
        ),
        migrations.RunPython(populate_has_children, migrations.RunPython.noop),
    ]

