# Generated by Django 3.2.25 on 2026-02-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0116_set_default_has_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='has_children',
            field=models.BooleanField(db_index=True, default=False, help_text='Flag indicating if this project has child projects (events).'),
        ),
    ]
