# Generated by Django 4.2.27 on 2026-03-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0117_alter_project_has_children"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_online",
            field=models.BooleanField(
                default=False,
                help_text="Whether the project takes place online",
                verbose_name="Is Online",
            ),
        ),
    ]
