# Generated by Django 4.2.27 on 2026-03-18 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0118_add_is_online_to_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        help_text="Maximum number of participants allowed to register (must be > 0)",
                        verbose_name="Maximum Participants",
                    ),
                ),
                (
                    "registration_end_date",
                    models.DateTimeField(
                        help_text="Date and time when registration closes. Timezone-aware (TIMESTAMPTZ), stored in UTC. Must be on or before the event's end_date.",
                        verbose_name="Registration End Date",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this registration configuration was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this registration configuration was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        help_text="The event project this registration configuration belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registration",
                        to="organization.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Registration",
                "verbose_name_plural": "Event Registrations",
            },
        ),
    ]
