# Generated by Django 4.2.27 on 2026-03-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0119_add_event_registration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventregistration",
            name="max_participants",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of participants allowed to register (must be > 0). May be null while the project is still a draft.",
                null=True,
                verbose_name="Maximum Participants",
            ),
        ),
        migrations.AlterField(
            model_name="eventregistration",
            name="registration_end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when registration closes. Timezone-aware (TIMESTAMPTZ), stored in UTC. Must be on or before the event's end_date. May be null while the project is still a draft.",
                null=True,
                verbose_name="Registration End Date",
            ),
        ),
    ]
