# Generated by Django 4.2.27 on 2026-03-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0120_allow_nullable_event_registration_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed"), ("full", "Full")],
                db_index=True,
                default="open",
                help_text="Lifecycle state of registration. 'open' — accepting sign-ups (default). 'closed' — organiser manually closed before end date. 'full' — system-set when max_participants reached; reverts to 'open' if a cancellation drops count below max.",
                max_length=10,
                verbose_name="Registration Status",
            ),
        ),
    ]
