# Generated by Django 4.2.27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0125_add_notify_admins_to_eventregistrationconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="organization.eventregistrationconfig",
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("checkbox", "Checkbox"),
                            ("option_select", "Option Select"),
                        ],
                        max_length=50,
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("is_required", models.BooleanField(default=False)),
                ("settings", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="RegistrationFieldOption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="organization.registrationfield",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddConstraint(
            model_name="registrationfield",
            constraint=models.UniqueConstraint(
                deferrable=models.Deferrable.DEFERRED,
                fields=["registration_config", "order"],
                name="unique_registrationfield_order_per_config",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationfieldoption",
            constraint=models.UniqueConstraint(
                deferrable=models.Deferrable.DEFERRED,
                fields=["field", "order"],
                name="unique_registrationfieldoption_order_per_field",
            ),
        ),
    ]
