# Generated by Django 4.2.27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0126_add_registrationfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationFieldAnswer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value_boolean", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="organization.registrationfield",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_answers",
                        to="organization.eventregistration",
                    ),
                ),
                (
                    "value_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="organization.registrationfieldoption",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registration Field Answer",
                "verbose_name_plural": "Registration Field Answers",
            },
        ),
        migrations.AlterUniqueTogether(
            name="registrationfieldanswer",
            unique_together={("registration", "field")},
        ),
    ]
