# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0127_add_registrationfieldanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationfieldoption",
            name="available_amount",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registrationfieldoption",
            name="max_amount_per_guest",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
