# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0128_registrationfieldoption_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationfield",
            name="label",
            field=models.CharField(default="", max_length=30),
        ),
    ]
