# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0130_registrationfield_label_backfill"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="registrationfield",
            constraint=models.UniqueConstraint(
                fields=("registration_config", "label"),
                name="unique_registrationfield_label_per_config",
            ),
        ),
    ]
