# Generated by Django 4.2.30 on 2026-05-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0131_registrationfield_label_constraint"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventregistration",
            options={
                "verbose_name": "Event Registration",
                "verbose_name_plural": "Event Registrations",
            },
        ),
        migrations.AlterModelOptions(
            name="eventregistrationconfig",
            options={
                "verbose_name": "Event Registration Config",
                "verbose_name_plural": "Event Registration Configs",
            },
        ),
        migrations.RemoveIndex(
            model_name="eventregistration",
            name="idx_ep_event_registration",
        ),
        migrations.AddField(
            model_name="registrationfieldoption",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registrationfieldoption",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eventregistrationconfig",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("closed", "Closed"),
                    ("full", "Full"),
                    ("ended", "Ended"),
                ],
                db_index=True,
                default="open",
                help_text="Lifecycle state of registration. 'open' — accepting sign-ups (default). 'closed' — organiser manually closed before end date. 'full' — system-set when max_participants reached; reverts to 'open' if a cancellation drops count below max. 'ended' — Python-side computed value only; NEVER stored here.",
                max_length=10,
                verbose_name="Registration Status",
            ),
        ),
        migrations.AlterField(
            model_name="registrationfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("checkbox", "Checkbox"),
                    ("option_select", "Option Select"),
                    ("inventory", "Inventory"),
                    ("time_slot_select", "Time Slot Select"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="registrationfield",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="registrationfield",
            name="label",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="registrationfieldanswer",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="registrationfieldoption",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(
                fields=["registration_config"], name="idx_ep_event_registration"
            ),
        ),
    ]
