# Generated by Django 4.2.30 on 2026-05-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0132_registrationfieldoption_timeslot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationfieldoption",
            name="title",
            field=models.CharField(default="", max_length=200),
        ),
    ]
