# Generated by Django 4.2.30 on 2026-05-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0133_alter_registrationfieldoption_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationfieldanswer",
            name="value_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
