# Generated by Django 4.2.30 on 2026-05-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0134_registrationfieldanswer_value_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="devlink_component",
            field=models.CharField(
                blank=True,
                help_text="Devlink component name from Webflow. Use the full component name including the language prefix (e.g. 'EnChErlangenLandingpage'). If the component has localized variants, include the En or De prefix — the system will swap it automatically based on the user's locale. If the component has no language prefix (e.g. 'Wasseraktionswochen'), it will be shown as-is for all languages.",
                max_length=128,
                null=True,
                verbose_name="Devlink component name",
            ),
        ),
    ]
