# Generated by Django 4.2.30 on 2026-06-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0137_eventregistrationconfig_registration_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="rating",
            field=models.SmallIntegerField(
                default=100,
                help_text="The larger the number, the more to the top this project will be displayed. Negative values downrank the project.",
                verbose_name="Rating",
            ),
        ),
    ]
