# Generated by Django 4.2.30 on 2026-06-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0138_alter_project_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistrationconfig",
            name="last_guest_email_sent_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=None,
                help_text="Timestamp of the last bulk email sent to event guests. NULL if no email has been sent.",
                null=True,
                verbose_name="Last Guest Email Sent At",
            ),
        ),
    ]
