# Generated by Django 4.2.30 on 2026-06-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0140_registrationfieldanswer_value_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("checkbox", "Checkbox"),
                    ("option_select", "Option Select"),
                    ("inventory", "Inventory"),
                    ("time_slot_select", "Time Slot Select"),
                    ("text", "Text"),
                ],
                max_length=50,
            ),
        ),
    ]
