# Generated by Django 4.2.30 on 2026-07-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0141_alter_registrationfield_field_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description_html",
            field=models.TextField(
                blank=True,
                help_text="Rich-text HTML description (Tiptap output)",
                null=True,
                verbose_name="Description HTML",
            ),
        ),
        migrations.AddField(
            model_name="projecttranslation",
            name="description_html_translation",
            field=models.TextField(
                blank=True,
                help_text="Translation of project's HTML description",
                null=True,
                verbose_name="Description HTML translation",
            ),
        ),
    ]
