# Generated by Django 4.2.27 on 2026-07-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0142_add_description_html_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="cancellation_reason",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Optional message provided by the guest when they cancelled.",
                null=True,
                verbose_name="Cancellation Reason",
            ),
        ),
    ]
