# Generated by Django 5.2.17 on 2026-08-26 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0144_alter_project_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrganizationFieldTagging",
        ),
    ]
