# Generated by Django 2.2.13 on 2020-08-22 21:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_uuid', models.UUIDField(help_text='Unique ID for each message connection', unique=True, verbose_name='Chat UUID')),
                ('is_active', models.BooleanField(default=True, help_text='Check if the chat between participants are active or not.If they are not active that means a user has blocked another person.', verbose_name='Is active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when participants started a messaging', verbose_name='Created at')),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='Time when one of the user has deactivated their chat.', null=True, verbose_name='Deactivated at')),
                ('participants', models.ManyToManyField(help_text='Points to users who participated in a chat.', related_name='message_participants', to=settings.AUTH_USER_MODEL, verbose_name='Participants')),
            ],
            options={
                'verbose_name_plural': 'Message Participants',
            },
        ),
    ]
