# Generated by Django 2.2.13 on 2020-08-22 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_messages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Content of a message', verbose_name='Content')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Time when message was sent', null=True, verbose_name='Sent at')),
                ('read_at', models.DateTimeField(blank=True, help_text='Time when all participants have read a messages', null=True, verbose_name='Read at')),
                ('updated_at', models.DateTimeField(blank=True, help_text='Time when sender updated a message', null=True, verbose_name='Updated at')),
                ('message_participant', models.ForeignKey(help_text='Points to a table where chat was initialized between participants', on_delete=django.db.models.deletion.CASCADE, related_name='participant_message', to='chat_messages.MessageParticipants', verbose_name='Message participant')),
                ('sender', models.ForeignKey(help_text='Points to user who sent a message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_sender', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
