# Generated by Django 2.2.13 on 2020-09-29 05:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat_messages", "0002_auto_20200922_1521"),
    ]

    operations = [
        migrations.AddField(
            model_name="messageparticipants",
            name="participants",
            field=models.ManyToManyField(
                help_text="Points to list users in a group",
                related_name="participant_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Participants",
            ),
        ),
    ]
