# Generated by Django 2.2.13 on 2020-08-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageparticipants',
            name='chat_uuid',
            field=models.UUIDField(blank=True, help_text='Unique ID for each message connection', null=True, unique=True, verbose_name='Chat UUID'),
        ),
    ]
