# Generated by Django 2.2.13 on 2020-09-29 05:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat_messages", "0003_messageparticipants_participants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messageparticipants",
            name="participant_one",
        ),
        migrations.RemoveField(
            model_name="messageparticipants",
            name="participant_two",
        ),
    ]
