# Generated by Django 2.2.13 on 2020-11-13 09:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat_messages", "0007_auto_20201112_2004"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messageparticipants",
            name="participants",
        ),
    ]
