# Generated by Django 2.2.13 on 2021-01-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_messages", "0008_remove_messageparticipants_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Check if the user is still part of the chat.",
                verbose_name="Is active?",
            ),
        ),
    ]
