# Generated by Django 2.2.20 on 2021-06-11 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chat_messages", "0011_messageparticipants_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messageparticipants",
            name="related_idea",
            field=models.ForeignKey(
                blank=True,
                help_text="If this chat is about an idea, this points to the idea",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_idea_message_participant",
                to="ideas.Idea",
                verbose_name="Related idea",
            ),
        ),
    ]
