# Generated by Django 2.2.28 on 2022-07-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0012_auto_20210611_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageparticipants',
            name='name',
            field=models.CharField(help_text='Name of the chat', max_length=128, verbose_name='chat_name'),
        ),
    ]
