# Generated by Django 2.2.28 on 2022-07-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0013_auto_20220714_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageparticipants',
            name='is_group',
            field=models.BooleanField(default=False, help_text='Is this a group chat?', verbose_name='is_group_chat'),
        ),
    ]
