# Generated by Django 2.2.28 on 2022-07-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0015_auto_20220714_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageparticipants',
            name='is_group',
            field=models.BooleanField(default=False, help_text='Is this a group chat?', verbose_name='Is group chat?'),
        ),
    ]
