# Generated by Django 3.2.16 on 2022-12-16 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_messages', '0015_auto_20220419_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageparticipants',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Points to the user that created the chat', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
    ]
