# Generated by Django 2.2.28 on 2022-07-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0016_auto_20220714_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageparticipants',
            name='is_group',
        ),
    ]
