# Generated by Django 2.2.28 on 2022-07-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0017_remove_messageparticipants_is_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageparticipants',
            name='is_group',
            field=models.BooleanField(default=False, help_text='Checks if the chat is a group chat or not', verbose_name='Is group?'),
        ),
    ]
