# Generated by Django 4.2.27 on 2026-07-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0018_manually_add_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="origin_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Primary key of the origin entity identified by origin_type.",
                null=True,
                verbose_name="Origin ID",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="origin_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Context that originated this message. Valid values: '' (no context), "
                    "'project', 'event_registration', 'organization', 'hub'. Blank means no origin context."
                ),
                max_length=32,
                verbose_name="Origin Type",
            ),
        ),
    ]
