# Generated by Django 3.2.18 on 2023-05-19 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0018_manually_add_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='chat',
            field=models.ForeignKey(help_text='Points to the chat that this user is a part of', on_delete=django.db.models.deletion.CASCADE, related_name='participant_participants', to='chat_messages.messageparticipants', verbose_name='Chat'),
        ),
    ]
