[tool.ruff]
extend-exclude = ['*/migrations']
ignore = [
    'E501', # since black does not format all long lines (e.g. comments, disable this lint)
    'F541' # f-strings without placeholder
]
# Ignore `F401` (import violations) in all `__init__.py` files, and in `path/to/file.py`.
[tool.ruff.per-file-ignores]
"**/__init__.py" = ["F401"]

[tool.black]
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
# ^/foo.py  # exclude a file named foo.py in the root of the project (in addition to the defaults)
^.*\b(migrations)\b.*$
'''
