# Generated by Django 2.2.11 on 2020-04-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("climateconnect_api", "0006_userprofile_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="url_slug",
            field=models.CharField(
                blank=True,
                help_text="slug for user URL",
                max_length=512,
                null=True,
                unique=True,
                verbose_name="URL Slug",
            ),
        ),
    ]
