# Generated by Django 2.2.11 on 2020-06-15 20:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("climateconnect_api", "0009_role_role_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="profile_image",
            new_name="image",
        ),
    ]
