# Generated by Django 2.2.13 on 2020-06-24 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("climateconnect_api", "0013_auto_20200624_1158"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skill",
            options={
                "ordering": ["id"],
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
            },
        ),
        migrations.AddField(
            model_name="skill",
            name="parent_skill",
            field=models.ForeignKey(
                blank=True,
                help_text="Points to the parent skill",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="skill_parent",
                to="climateconnect_api.Skill",
                verbose_name="Parent Skill",
            ),
        ),
    ]
