# Generated by Django 2.2.13 on 2020-07-02 07:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("climateconnect_api", "0016_role_explanation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={
                "ordering": ["id"],
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
            },
        ),
    ]
