# Generated by Django 2.2.11 on 2020-07-07 07:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("climateconnect_api", "0017_auto_20200702_0728"),
        ("climateconnect_api", "0013_auto_20200701_0413"),
    ]

    operations = []
