# Generated by Django 2.2.13 on 2020-07-06 14:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("climateconnect_api", "0017_auto_20200702_0728"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "ordering": ["-id"],
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
