# Generated by Django 2.2.13 on 2020-07-07 13:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("climateconnect_api", "0018_auto_20200706_1450"),
        ("climateconnect_api", "0018_merge_20200707_0751"),
    ]

    operations = []
