# Generated by Django 2.2.13 on 2020-07-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("climateconnect_api", "0020_userprofile_has_logged_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="details",
            field=models.CharField(
                blank=True,
                help_text="Additional details about the skill",
                max_length=128,
                null=True,
                verbose_name="Details",
            ),
        ),
    ]
