# Generated by Django 2.2.13 on 2020-07-23 04:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("climateconnect_api", "0021_userprofile_verification_key"),
        ("climateconnect_api", "0021_skill_details"),
    ]

    operations = []
