# Generated by Django 2.2.13 on 2020-07-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("climateconnect_api", "0026_auto_20200724_1010"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="key",
            field=models.CharField(
                blank=True,
                help_text="Key of a skill",
                max_length=512,
                null=True,
                verbose_name="Key",
            ),
        ),
    ]
