# Generated by Django 2.2.13 on 2020-11-12 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("climateconnect_api", "0035_userprofile_email_on_new_project_follower"),
    ]

    operations = [
        migrations.AddField(
            model_name="usernotification",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Time when the notification was sent to the user",
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
    ]
