# Generated by Django 2.2.13 on 2020-11-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("climateconnect_api", "0036_usernotification_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="email_on_group_chat_message",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Check if user wants to receive emails when they receive a group chat message",
                null=True,
                verbose_name="Email on group chat message",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email_on_private_chat_message",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Check if user wants to receive emails when they receive a private chat message",
                null=True,
                verbose_name="Email on private chat message",
            ),
        ),
    ]
