# Generated by Django 2.2.13 on 2020-12-11 07:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("climateconnect_api", "0042_auto_20201207_2153"),
        ("climateconnect_api", "0042_auto_20201207_0230"),
    ]

    operations = []
