# Generated by Django 2.2.18 on 2021-04-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("climateconnect_api", "0055_auto_20210408_0532"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="details_de_translation",
            field=models.CharField(
                blank=True,
                help_text="Deutsch translation for details columns",
                max_length=128,
                null=True,
                verbose_name="Details DE translation",
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="name_de_translation",
            field=models.CharField(
                blank=True,
                help_text="Deutsch translation of name column",
                max_length=512,
                null=True,
                verbose_name="Name DE translation",
            ),
        ),
    ]
