# Generated by Django 2.2.18 on 2021-04-13 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("climateconnect_api", "0056_auto_20210408_0541"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="language",
            field=models.ForeignKey(
                blank=True,
                help_text="Points to user's original language",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile_language",
                to="climateconnect_api.Language",
                verbose_name="Language",
            ),
        ),
    ]
