# Generated by Django 2.2.13 on 2021-04-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("climateconnect_api", "0057_userprofile_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofiletranslation",
            name="is_manual_translation",
            field=models.BooleanField(
                default=False,
                help_text="Did the user manually translate this or was it automatically translated with DeepL?",
                verbose_name="Is manual translation?",
            ),
        ),
    ]
