# Generated by Django 2.2.18 on 2021-06-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climateconnect_api', '0060_auto_20210420_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(0, 'broadcast'), (1, 'private_message'), (2, 'project_comment'), (3, 'reply_to_project_comment'), (4, 'project_follower'), (5, 'project_update_post'), (6, 'post_comment'), (7, 'reply_to_post_comment'), (8, 'group_message'), (9, 'join_project_request'), (10, 'project_join_request_approved')], default=0, help_text='type of notification', verbose_name='Notification type'),
        ),
    ]
