# Generated by Django 2.2.24 on 2021-09-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climateconnect_api', '0065_userprofile_email_on_idea_join'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_guid', models.CharField(blank=True, help_text='Guid of the visitor. A randomly generated uuid', max_length=36, null=True, verbose_name='Visitor Guid')),
                ('visitor_ip', models.CharField(blank=True, help_text='IP of the visitor', max_length=39, null=True, verbose_name="Visitor's IP")),
                ('visitor_ip_country', models.CharField(blank=True, help_text='Country of the IP of the visitor', max_length=39, null=True, verbose_name="IP's Country")),
                ('visitor_ip_city', models.CharField(blank=True, help_text='City of the IP of the visitor', max_length=39, null=True, verbose_name="IP's City")),
                ('visit_url', models.CharField(help_text="Visitor's URL", max_length=4000, verbose_name='Visitor Entry Url')),
                ('visit_time', models.DateTimeField(help_text='Time at which the visit occured')),
                ('origin', models.TextField(blank=True, help_text="Visitor's origin of visit", max_length=4000, null=True, verbose_name='Visitor Origin')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when language was created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time when language object was updated', verbose_name='Updated at')),
            ],
        ),
    ]
