# Generated by Django 2.2.20 on 2021-09-20 21:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("climateconnect_api", "0061_auto_20210916_1003"),
        ("climateconnect_api", "0065_userprofile_email_on_idea_join"),
    ]

    operations = []
