# Generated by Django 2.2.24 on 2021-09-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climateconnect_api', '0066_siteanalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteanalytics',
            name='visitor_is_authenticated',
            field=models.BooleanField(default=False, help_text='Indicates whether the visitor is authenticated or not', verbose_name='Visitor is Authenticated'),
        ),
    ]
