# Generated by Django 2.2.24 on 2021-10-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("climateconnect_api", "0066_merge_20210920_2136"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={},
        ),
        migrations.AlterModelOptions(
            name="usernotification",
            options={"verbose_name_plural": "User notifications"},
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.IntegerField(
                choices=[
                    (0, "broadcast"),
                    (1, "private_message"),
                    (2, "project_comment"),
                    (3, "reply_to_project_comment"),
                    (4, "project_follower"),
                    (5, "project_update_post"),
                    (6, "post_comment"),
                    (7, "reply_to_post_comment"),
                    (8, "group_message"),
                    (9, "mention"),
                    (11, "idea_comment"),
                    (12, "reply_to_idea_comment"),
                    (13, "person_joined_idea"),
                ],
                default=0,
                help_text="type of notification",
                verbose_name="Notification type",
            ),
        ),
    ]
