# Generated by Django 2.2.24 on 2021-12-13 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("climateconnect_api", "0075_auto_20211129_1403"),
        ("climateconnect_api", "0076_badge_step"),
    ]

    operations = []
