# Generated by Django 2.2.24 on 2022-01-01 22:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("climateconnect_api", "0077_merge_20211213_1307"),
        ("climateconnect_api", "0066_auto_20210724_1451"),
    ]

    operations = []
