# Generated by Django 2.2.24 on 2022-01-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("climateconnect_api", "0078_merge_20220101_2230"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.IntegerField(
                choices=[
                    (0, "broadcast"),
                    (1, "private_message"),
                    (2, "project_comment"),
                    (3, "reply_to_project_comment"),
                    (4, "project_follower"),
                    (5, "project_update_post"),
                    (6, "post_comment"),
                    (7, "reply_to_post_comment"),
                    (8, "group_message"),
                    (9, "join_project_request"),
                    (10, "project_join_request_approved"),
                    (14, "mention"),
                    (15, "project_like"),
                    (11, "idea_comment"),
                    (12, "reply_to_idea_comment"),
                    (13, "person_joined_idea"),
                ],
                default=0,
                help_text="type of notification",
                verbose_name="Notification type",
            ),
        ),
    ]
