# Generated by Django 2.2.24 on 2022-01-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climateconnect_api', '0078_auto_20220120_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_on_new_post_like',
            field=models.BooleanField(blank=True, default=True, help_text='Check if user wants to receive emails when somebody likes a post on their project', null=True, verbose_name='Email on new post like'),
        ),
    ]
