# Generated by Django 2.2.28 on 2022-05-27 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0012_auto_20220401_0049'),
        ('climateconnect_api', '0081_userprofile_email_on_join_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInterests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Description why user is interested in this hub', max_length=256, null=True, verbose_name='Description about the Interest')),
                ('hub_interested_in', models.ForeignKey(help_text='Points to (sector) hub', on_delete=django.db.models.deletion.CASCADE, related_name='profile_interests', to='hubs.Hub', verbose_name='(sector) hub')),
                ('user_profile', models.ForeignKey(help_text='Points to user profile object', on_delete=django.db.models.deletion.CASCADE, related_name='profile_interests', to='climateconnect_api.UserProfile', verbose_name='User profile')),
            ],
            options={
                'verbose_name': 'User profile interest',
                'index_together': {('user_profile', 'hub_interested_in')},
            },
        ),
    ]
