# Generated by Django 2.2.28 on 2022-05-31 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climateconnect_api', '0082_userprofileinterests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInterests',
        ),
    ]
