# Generated by Django 2.2.28 on 2022-06-15 14:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0012_auto_20220401_0049'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('climateconnect_api', '0082_userinterests'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userinterests',
            unique_together={('user', 'hub')},
        ),
        migrations.AlterIndexTogether(
            name='userinterests',
            index_together=set(),
        ),
    ]
