# Generated by Django 3.2.14 on 2022-08-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climateconnect_api', '0083_auto_20220805_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_on_new_organization_follower',
            field=models.BooleanField(blank=True, default=True, help_text='Check if user wants to receive emails when somebody follows their organization', null=True, verbose_name='Email on new organization follower'),
        ),
    ]
