# Generated by Django 2.2.28 on 2022-06-02 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hubs', '0012_auto_20220401_0049'),
        ('climateconnect_api', '0083_delete_userprofileinterests'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Description why user is interested in this hub', max_length=256, null=True, verbose_name='Description about the Interest')),
                ('hub_interested_in', models.ForeignKey(help_text='Points to (sector) hub', on_delete=django.db.models.deletion.CASCADE, related_name='profile_interests', to='hubs.Hub', verbose_name='(sector) hub')),
                ('user', models.ForeignKey(help_text='Points to user object', on_delete=django.db.models.deletion.CASCADE, related_name='user_interests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User interest',
                'index_together': {('user', 'hub_interested_in')},
            },
        ),
    ]
