# Generated by Django 3.2.14 on 2022-08-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climateconnect_api', '0083_faqsection_is_on_about_page'),
        ('climateconnect_api', '0085_auto_20220810_1400'),
    ]

    operations = [
    ]
