# Generated by Django 3.2.14 on 2022-08-08 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0097_orgprojectpublished'),
        ('climateconnect_api', '0085_auto_20220808_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='org_project_published',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_org_project_published', to='organization.orgprojectpublished', verbose_name='Org Project Published'),
        ),
    ]
