# Generated by Django 3.2.14 on 2022-09-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climateconnect_api', '0085_auto_20220810_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='examine_text',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='examine_text_de',
        ),
    ]
