# Generated by Django 3.2.14 on 2022-08-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("climateconnect_api", "0085_auto_20220810_1400"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="badge",
            name="examine_text",
        ),
        migrations.RemoveField(
            model_name="badge",
            name="examine_text_de",
        ),
        migrations.AddField(
            model_name="faqsection",
            name="is_on_about_page",
            field=models.BooleanField(
                default=False,
                help_text="Identifies the section that should be shown on the about page faq section",
                verbose_name="Is shown on about page",
            ),
        ),
    ]
