# Generated by Django 3.2.14 on 2022-08-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climateconnect_api', '0086_alter_notification_org_project_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_on_new_project_from_followed_org',
            field=models.BooleanField(blank=True, default=True, help_text='Check if user wants to receive emails when an org they follow publishes a project', null=True, verbose_name='Email on new organization project published'),
        ),
    ]
