# Generated by Django 3.2.14 on 2022-08-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climateconnect_api', '0086_merge_20220827_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='examine_text',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='examine_text_de',
        ),
    ]
