# Generated by Django 3.2.15 on 2022-10-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climateconnect_api', '0087_socialmediachannel_socialmedialink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediachannel',
            name='social_media_name',
        ),
        migrations.AddField(
            model_name='socialmediachannel',
            name='facebook_link',
            field=models.CharField(default='', help_text='Points to the social media facebook', max_length=256, verbose_name='Facebook Link'),
        ),
        migrations.AddField(
            model_name='socialmediachannel',
            name='instagram_link',
            field=models.CharField(default='', help_text='Points to the social media instagram', max_length=256, verbose_name='Instagram Link'),
        ),
        migrations.AddField(
            model_name='socialmediachannel',
            name='linkedin_link',
            field=models.CharField(default='', help_text='Points to the social media linkedin', max_length=256, verbose_name='LinkedIn Link'),
        ),
        migrations.AddField(
            model_name='socialmediachannel',
            name='twitter_link',
            field=models.CharField(default='', help_text='Points to the social media twitter', max_length=256, verbose_name='Twitter Link'),
        ),
        migrations.AddField(
            model_name='socialmediachannel',
            name='youtube_link',
            field=models.CharField(default='', help_text='Points to the social media youtube', max_length=256, verbose_name='Youtube Link'),
        ),
    ]
