# Generated by Django 3.2.15 on 2022-09-29 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0097_delete_orgprojectpublished"),
        ("climateconnect_api", "0088_alter_notification_org_project_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="org_project_published",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_org_project_published",
                to="organization.projectparents",
                verbose_name="Org Project Published",
            ),
        ),
    ]
