# Generated by Django 3.2.15 on 2022-10-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climateconnect_api', '0088_auto_20221007_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediachannel',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='socialmediachannel',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='socialmediachannel',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='socialmediachannel',
            name='twitter_link',
        ),
        migrations.RemoveField(
            model_name='socialmediachannel',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='socialmediachannel',
            name='social_media_name',
            field=models.CharField(default='', help_text='Points to name of the social media', max_length=256, verbose_name='Social Media Channel'),
        ),
    ]
