# Generated by Django 3.2.15 on 2022-10-10 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climateconnect_api', '0090_auto_20221010_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediachannel',
            name='key',
        ),
    ]
