# Generated by Django 3.2.15 on 2022-10-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climateconnect_api', '0091_remove_socialmediachannel_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediachannel',
            name='ask_for_full_website',
            field=models.BooleanField(default=False, help_text='Checks if user should only provide a handle or full link', verbose_name='Ask For Full Website'),
        ),
        migrations.AddField(
            model_name='socialmediachannel',
            name='base_url',
            field=models.CharField(default='', help_text='URL of the medium e.g. "https://twitter.com/"', max_length=256, verbose_name='Base URL'),
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='handle',
            field=models.CharField(default='', help_text='Handle of the social media, e.g. @ConnectClimate', max_length=256, verbose_name='Social Media Handle'),
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='url',
            field=models.CharField(default='', help_text='Full url of the social media e.g. https://twitter.com/ConnectClimate', max_length=256, verbose_name='Social Media URL'),
        ),
        migrations.AlterField(
            model_name='socialmediachannel',
            name='social_media_name',
            field=models.CharField(default='', help_text='Name of the medium e.g. "Twitter"', max_length=256, verbose_name='Social Media Channel'),
        ),
    ]
