# Generated by Django 3.2.15 on 2022-11-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climateconnect_api', '0087_socialmediachannel_socialmedialink'),
        ('climateconnect_api', '0092_auto_20221115_0946'),
    ]

    operations = [
    ]
