# Generated by Django 3.2.15 on 2022-10-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climateconnect_api', '0092_auto_20221012_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='handle',
            field=models.CharField(blank=True, default='', help_text='Handle of the social media, e.g. @ConnectClimate', max_length=256, verbose_name='Social Media Handle'),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='url',
            field=models.CharField(blank=True, default='', help_text='Full url of the social media e.g. https://twitter.com/ConnectClimate', max_length=256, verbose_name='Social Media URL'),
        ),
    ]
