# Generated by Django 3.2.23 on 2025-01-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0033_remove_hubtheme_background_paper'),
        ('climateconnect_api', '0094_alter_notification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='related_hubs',
            field=models.ManyToManyField(blank=True, related_name='user_related_hubs', to='hubs.Hub'),
        ),
    ]
