# Generated by Django 3.2.23 on 2025-01-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0035_auto_20250103_0002'),
        ('climateconnect_api', '0094_alter_notification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='related_hubs',
            field=models.ManyToManyField(blank=True, related_name='related_hubs', to='hubs.Hub'),
        ),
    ]
