# Generated by Django 3.2.25 on 2025-06-24 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hubs", "0036_hub_landing_page_component"),
        ("climateconnect_api", "0095_userprofile_related_hubs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donationgoal",
            name="amount",
        ),
        migrations.AddField(
            model_name="donationgoal",
            name="call_to_action_link",
            field=models.CharField(
                blank=True,
                help_text="Link for the call to action, e.g. 'https://climatehub.earth/300'",
                max_length=512,
                null=True,
                verbose_name="Call to Action Link",
            ),
        ),
        migrations.AddField(
            model_name="donationgoal",
            name="call_to_action_text",
            field=models.CharField(
                blank=True,
                help_text="Text for the call to action, e.g. 'Donate now!'",
                max_length=512,
                null=True,
                verbose_name="Call to Action Text",
            ),
        ),
        migrations.AddField(
            model_name="donationgoal",
            name="call_to_action_text_de_translation",
            field=models.CharField(
                blank=True,
                help_text="German translation for text for the call to action, e.g. 'Jetzt spenden!'",
                max_length=512,
                null=True,
                verbose_name="Call to Action Text (German Translation)",
            ),
        ),
        migrations.AddField(
            model_name="donationgoal",
            name="current_amount",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The current amount including the unit (e.g. '500€')",
                verbose_name="Current Amount",
            ),
        ),
        migrations.AddField(
            model_name="donationgoal",
            name="goal_amount",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The goal amount including the unit (e.g. '1000€')",
                verbose_name="Goal Amount",
            ),
        ),
        migrations.AddField(
            model_name="donationgoal",
            name="hub",
            field=models.ForeignKey(
                blank=True,
                help_text="Choose a hub if the donation goal should only be shown on one hub",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donationgoal_hub",
                to="hubs.hub",
                verbose_name="Hub",
            ),
        ),
        migrations.AddField(
            model_name="donationgoal",
            name="unit",
            field=models.CharField(
                blank=True,
                default="€",
                help_text="Unit of the donation goal, e.g. '€'",
                max_length=64,
                null=True,
                verbose_name="Unit",
            ),
        ),
    ]
