# Generated by Django 3.2.25 on 2025-08-06 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0112_auto_20250806_1052'),
        ('climateconnect_api', '0096_auto_20250624_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileSectorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when mapping was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time when mapping was updated', verbose_name='Updated At')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='The bigger the number, the more to the top this sector will be displayed', verbose_name='Position of tag')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userProfile_sector_mapping', to='organization.sector')),
                ('userProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userProfile_sector_mapping', to='climateconnect_api.userprofile')),
            ],
            options={
                'verbose_name': 'UserProfile Sector Mapping',
                'ordering': ['id'],
                'unique_together': {('sector', 'userProfile')},
            },
        ),
    ]
