# Generated by Django 3.2.25 on 2025-12-04 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0114_merge_0112_auto_20250806_1052_0113_auto_20250807_0835'),
        ('climateconnect_api', '0098_rename_userprofile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='path',
            field=models.TextField(blank=True, help_text='The URL path (including query string) where feedback was submitted', null=True, verbose_name='Path'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_agent',
            field=models.TextField(blank=True, help_text='The user agent of the browser when feedback was submitted', null=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='userprofilesectormapping',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_sector_mapping', to='organization.sector'),
        ),
        migrations.AlterField(
            model_name='userprofilesectormapping',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_sector_mapping', to='climateconnect_api.userprofile'),
        ),
    ]
