# Generated by Django 4.2.27 on 2026-04-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("climateconnect_api", "0099_add_context_to_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="auth_method",
            field=models.CharField(
                choices=[("password", "Password"), ("otp", "OTP")],
                default="password",
                help_text="Authentication method preferred by the user. 'password' = password-based login (default for all existing users); 'otp' = passwordless OTP-based login.",
                max_length=8,
                verbose_name="Auth Method",
            ),
        ),
    ]
