# Generated by Django 4.2.27 on 2026-06-03

from django.db import migrations


def rename_creator_role(apps, schema_editor):
    Role = apps.get_model("climateconnect_api", "Role")
    creator_role = Role.objects.filter(name="Creator").first()
    if creator_role:
        creator_role.name = "Super-Admin"
        creator_role.save()


class Migration(migrations.Migration):

    dependencies = [
        ("climateconnect_api", "0100_userprofile_auth_method"),
    ]

    operations = [
        migrations.RunPython(rename_creator_role, migrations.RunPython.noop),
    ]
