# Generated by Django 4.2.30 on 2026-08-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("climateconnect_api", "0101_rename_creator_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentshares",
            name="shared_via",
            field=models.IntegerField(
                choices=[
                    (0, "facebook"),
                    (1, "fb_messenger"),
                    (2, "twitter"),
                    (3, "whatsapp"),
                    (4, "linkedin"),
                    (5, "reddit"),
                    (6, "telegram"),
                    (7, "e_mail"),
                    (8, "link"),
                    (9, "native_share_dialog_of_device"),
                    (10, "bluesky"),
                ],
                default=8,
                help_text="Way in which the content was shared",
                verbose_name="Shared Via",
            ),
        ),
    ]
