# Generated by Django 4.2.27 on 2026-04-20 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Email address the code was sent to.",
                        max_length=254,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        help_text="SHA-256 hash of the raw 6-digit code. Raw code is never stored.",
                        max_length=64,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        help_text="32-byte hex random value; ties the token to the specific browser tab.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Expiry time — set to now + 15 minutes on creation.",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set on first successful use. Null means the token has not been used yet.",
                        null=True,
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Incremented on each failed verification attempt. Token is locked at 5.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set after user lookup; null while email is unrecognised (enumeration prevention).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Login Token",
                "verbose_name_plural": "Login Tokens",
                "indexes": [
                    models.Index(fields=["email"], name="auth_app_lo_email_8495de_idx"),
                    models.Index(
                        fields=["expires_at"], name="auth_app_lo_expires_baa54a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoginAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Email address used in the attempt.",
                        max_length=254,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                            ("exhausted", "Exhausted"),
                            ("resent", "Resent"),
                        ],
                        help_text="Outcome of the login event.",
                        max_length=16,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Anonymised IP address (last octet zeroed for IPv4). Anonymisation is applied in the view/service layer before saving.",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="User-Agent string from the request. Optional — collected for security purposes.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp of the event. Indexed for retention cleanup and time-range queries.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null if email was not found at the time of the event.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Login Audit Log",
                "verbose_name_plural": "Login Audit Logs",
                "indexes": [
                    models.Index(fields=["email"], name="auth_app_lo_email_161142_idx"),
                    models.Index(
                        fields=["created_at"], name="auth_app_lo_created_f52fa4_idx"
                    ),
                ],
            },
        ),
    ]
