# Generated by Django 2.2.20 on 2021-07-02 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climate_match', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Answer text', max_length=1024, verbose_name='Answer')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when pre-defined answers were created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time when answer was updated', verbose_name='Updated at')),
                ('question', models.ForeignKey(help_text='Points to question with predefined answers', on_delete=django.db.models.deletion.CASCADE, related_name='answer_question', to='climate_match.Question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
    ]
