# Generated by Django 2.2.20 on 2021-07-27 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("climate_match", "0002_auto_20210727_0447"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserQuestionAnswer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Time when user first answered question.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Time when user updated their answer",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "answers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Points choices that user made.",
                        related_name="user_ans_metadata",
                        to="climate_match.AnswerMetaData",
                        verbose_name="Answers",
                    ),
                ),
                (
                    "predefined_answer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Points to predefined answers we show customers",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_predefined_answer",
                        to="climate_match.Answer",
                        verbose_name="Predefined Answer",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="Points to question we ask users",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_question",
                        to="climate_match.Question",
                        verbose_name="Question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Points user who answered questions",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_qna",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User question answer",
                "verbose_name_plural": "User question answers",
            },
        ),
    ]
