# Generated by Django 2.2.20 on 2021-07-02 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('climate_match', '0002_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(help_text='What should be the weight of a resource. Resources may contain projects, ideas, organization etc.This will help us sort projects, ideas, organization etc easily.', verbose_name='Weight')),
                ('reference_id', models.IntegerField(blank=True, help_text='Points to ID of a reference. Example: Hub ID that user choses.', null=True, verbose_name='Reference ID')),
                ('reference_type', models.ForeignKey(help_text='Points to table that we will be ranking. i.e.: Points to Hubs, Idea, Organization, Project and Skills', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Reference type')),
            ],
            options={
                'verbose_name': 'Answer meta data',
                'verbose_name_plural': 'Answer meta data',
            },
        ),
    ]
