# Generated by Django 2.2.20 on 2021-07-06 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climate_match', '0005_answertranslation_questiontranslation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answermetadata',
            options={'verbose_name': 'Answer metadata', 'verbose_name_plural': 'Answer metadata'},
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.ForeignKey(blank=True, help_text="Points to a model who's weight should increase. Example: Hubs, Predefined Answer, Skills", null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType', verbose_name='Answer type'),
        ),
    ]
