# Generated by Django 2.2.24 on 2021-09-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("climate_match", "0006_question_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="step",
            field=models.IntegerField(
                blank=True,
                help_text="At which step should we ask this particular question?",
                null=True,
                verbose_name="Step",
            ),
        ),
    ]
