# Generated by Django 2.2.20 on 2021-07-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_match', '0006_auto_20210706_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_metadata',
            field=models.ManyToManyField(help_text='Points to answer metadata table', to='climate_match.AnswerMetaData', verbose_name='Answer metadata'),
        ),
    ]
