# Generated by Django 2.2.20 on 2021-07-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_match', '0007_answer_answer_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionanswer',
            name='answers',
            field=models.ManyToManyField(blank=True, help_text='Points choices that user made.', related_name='user_ans_metadata', to='climate_match.AnswerMetaData', verbose_name='Answers'),
        ),
    ]
