# Generated by Django 2.2.24 on 2021-11-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("climate_match", "0009_question_minimum_choices_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquestionanswer",
            name="token",
            field=models.UUIDField(
                blank=True,
                help_text="Unique token to store for user who are not logged in.",
                null=True,
                unique=True,
                verbose_name="Token",
            ),
        ),
    ]
