# Generated by Django 3.2 on 2022-04-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("climate_match", "0013_userquestionanswer_hub"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="answermetadata",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="answertranslation",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="question",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="questiontranslation",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="userquestionanswer",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
