# Generated by Django 2.2.13 on 2020-12-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hubs", "0003_auto_20201221_0836"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hub",
            name="segway_text",
            field=models.TextField(
                help_text="Segway text between the info and the solutions",
                verbose_name="Segway text",
            ),
        ),
    ]
