# Generated by Django 2.2.18 on 2021-05-10 03:24

from django.db import migrations, models
import hubs.models.hub


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0010_auto_20210422_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo image for ideasboard, projects etc', null=True, upload_to=hubs.models.hub.hub_image_path, verbose_name='Logo'),
        ),
    ]
