# Generated by Django 2.2.24 on 2022-01-28 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hubs", "0011_auto_20210505_2011"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalAmbassador",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Ambassador title",
                        max_length=1024,
                        null=True,
                        verbose_name="Ambassador title",
                    ),
                ),
                (
                    "title_de",
                    models.CharField(
                        blank=True,
                        help_text="The german translation of the ambassador's title",
                        max_length=1024,
                        null=True,
                        verbose_name="Ambassador title german",
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        blank=True,
                        help_text="Points to hub the user is ambassador of",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ambassador_hub",
                        to="hubs.Hub",
                        verbose_name="Hub",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Points to user who is ambassador of the hub",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ambassador_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Local Ambassador",
                "verbose_name_plural": "Local Ambassadors",
            },
        ),
    ]
