# Generated by Django 3.2.15 on 2022-09-21 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hubs", "0012_localambassador"),
        ("hubs", "0013_auto_20220419_0744"),
    ]

    operations = []
