# Generated by Django 3.2.15 on 2022-09-22 08:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hubs", "0015_auto_20220921_1617"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hubambassador",
            options={
                "verbose_name": "Hub Ambassador",
                "verbose_name_plural": "Hub Ambassadors",
            },
        ),
    ]
