# Generated by Django 3.2.18 on 2023-02-27 06:37

from django.db import migrations, models
import hubs.models.hub


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0016_alter_hubambassador_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='custom_footer_image',
            field=models.ImageField(blank=True, help_text='Custom image to show in the footer of this specific hub, e.g. to display a grant to financed the start of the hub', null=True, upload_to=hubs.models.hub.hub_footer_image_path, verbose_name='Custom footer image'),
        ),
    ]
