# Generated by Django 3.2.23 on 2024-10-23 13:39

from django.db import migrations, models
import django.db.models.deletion
import hubs.models.hub


class Migration(migrations.Migration):

    dependencies = [
        ('climateconnect_api', '0094_alter_notification_options'),
        ('organization', '0103_alter_projectmember_availability'),
        ('hubs', '0018_auto_20240920_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubSupporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Supporter name', max_length=1024, null=True, verbose_name='Supporter name')),
                ('subtitle', models.CharField(blank=True, help_text='Supporter subtitle', max_length=1024, null=True, verbose_name='subtitle')),
                ('logo', models.ImageField(blank=True, help_text='Supporter logo', null=True, upload_to=hubs.models.hub.hub_image_path, verbose_name='Logo')),
                ('importance', models.PositiveSmallIntegerField(default=100, help_text='The larger the number, the more to the top this hub will be displayed on the hubs overview page', verbose_name='Importance (1-100)')),
                ('hub', models.ForeignKey(blank=True, help_text='Supported Hubs by the Supporter', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporter_hub', to='hubs.hub', verbose_name='Hub')),
                ('language', models.ForeignKey(blank=True, help_text='The original language of the supporter', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporter_language', to='climateconnect_api.language', verbose_name='Language')),
                ('organization', models.ForeignKey(blank=True, help_text="Points to the supporter's organization", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporter_organization', to='organization.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Hub Supporter',
                'verbose_name_plural': 'Hub Supporter',
            },
        ),
        migrations.CreateModel(
            name='HubSupporterTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_translation', models.CharField(blank=True, help_text='Translation of name column', max_length=1024, null=True, verbose_name='Name translation')),
                ('subtitle_translation', models.CharField(blank=True, help_text='Translation of subtitle column', max_length=1024, null=True, verbose_name='Subtitle translation')),
                ('HubSupporter', models.ForeignKey(help_text='Points to Hub Support table', on_delete=django.db.models.deletion.CASCADE, related_name='translate_hub_supporter', to='hubs.hubsupporter', verbose_name='Hub Supporter')),
                ('language', models.ForeignKey(help_text='Points to language table', on_delete=django.db.models.deletion.CASCADE, related_name='hub_supporter_translation_lang', to='climateconnect_api.language', verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Hub supporter translation',
                'verbose_name_plural': 'Hub supporter translations',
                'unique_together': {('HubSupporter', 'language')},
            },
        ),
    ]
