# Generated by Django 3.2.23 on 2024-10-24 11:44

from django.db import migrations, models
import hubs.models.hub


class Migration(migrations.Migration):

    dependencies = [
        ('climateconnect_api', '0094_alter_notification_options'),
        ('hubs', '0019_hubsupporter_hubsupportertranslation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hubsupportertranslation',
            old_name='HubSupporter',
            new_name='hub_supporter',
        ),
        migrations.AlterField(
            model_name='hubsupporter',
            name='logo',
            field=models.ImageField(blank=True, help_text='Supporter logo', null=True, upload_to=hubs.models.hub.hub_supporter_logo_path, verbose_name='Logo'),
        ),
        migrations.AlterUniqueTogether(
            name='hubsupportertranslation',
            unique_together={('hub_supporter', 'language')},
        ),
    ]
