# Generated by Django 3.2.23 on 2024-10-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0104_project_hubs'),
        ('hubs', '0019_remove_hub_filter_parent_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='filter_parent_tags',
            field=models.ManyToManyField(blank=True, help_text='Only project with these parent tags will be shown in the hub', related_name='hub_parent_tags', to='organization.ProjectTags', verbose_name='Hub categories'),
        ),
    ]
