# Generated by Django 3.2.23 on 2024-11-20 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0020_auto_20241024_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Theme name', max_length=1024, null=True, verbose_name='Theme name')),
                ('primary_color', models.CharField(blank=True, help_text='primary_color', max_length=1024, null=True, verbose_name='primary_color')),
                ('secondary_color', models.CharField(blank=True, help_text='secondary_color', max_length=1024, null=True, verbose_name='secondary_color')),
            ],
            options={
                'verbose_name': 'Hub Theme',
                'verbose_name_plural': 'Hub Theme',
            },
        ),
        migrations.AlterModelOptions(
            name='hubsupporter',
            options={'ordering': ['-importance'], 'verbose_name': 'Hub Supporter', 'verbose_name_plural': 'Hub Supporter'},
        ),
        migrations.AlterField(
            model_name='hub',
            name='importance',
            field=models.PositiveSmallIntegerField(default=100, help_text='The larger the number, the more to the top this hub will be displayed on the hubs overview page.(Putting importance to 0 will hide the hub)', verbose_name='Importance (0-100)'),
        ),
        migrations.AlterField(
            model_name='hubsupporter',
            name='hub',
            field=models.ForeignKey(blank=True, help_text='Supported Hub by the Supporter', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporter_hub', to='hubs.hub', verbose_name='Hub'),
        ),
        migrations.AlterField(
            model_name='hubsupporter',
            name='importance',
            field=models.PositiveSmallIntegerField(default=100, help_text='The larger the number, the more to the top this hub will be displayed on the hubs overview page. (Putting importance to 0 will hide the supporter)', verbose_name='Importance (0-100)'),
        ),
        migrations.AddField(
            model_name='hub',
            name='theme',
            field=models.ForeignKey(blank=True, help_text='The theme for the hub', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hub_theme', to='hubs.hubtheme', verbose_name='hub_theme'),
        ),
    ]
