# Generated by Django 3.2.23 on 2024-11-13 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0020_auto_20241024_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hubsupporter',
            options={'ordering': ['-importance'], 'verbose_name': 'Hub Supporter', 'verbose_name_plural': 'Hub Supporter'},
        ),
        migrations.AlterField(
            model_name='hub',
            name='importance',
            field=models.PositiveSmallIntegerField(default=100, help_text='The larger the number, the more to the top this hub will be displayed on the hubs overview page.(Putting importance to 0 will hide the hub)', verbose_name='Importance (0-100)'),
        ),
        migrations.AlterField(
            model_name='hubsupporter',
            name='hub',
            field=models.ForeignKey(blank=True, help_text='Supported Hub by the Supporter', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporter_hub', to='hubs.hub', verbose_name='Hub'),
        ),
        migrations.AlterField(
            model_name='hubsupporter',
            name='importance',
            field=models.PositiveSmallIntegerField(default=100, help_text='The larger the number, the more to the top this hub will be displayed on the hubs overview page. (Putting importance to 0 will hide the supporter)', verbose_name='Importance (0-100)'),
        ),
    ]
