# Generated by Django 3.2.23 on 2024-11-25 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0021_auto_20241120_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubThemeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.CharField(blank=True, help_text='main color', max_length=7, null=True, verbose_name='main color')),
                ('light', models.CharField(blank=True, help_text='light color', max_length=7, null=True, verbose_name='light color')),
                ('lightHover', models.CharField(blank=True, help_text='lightHover color', max_length=7, null=True, verbose_name='lightHover color')),
                ('extraLight', models.CharField(blank=True, help_text='extraLight color', max_length=7, null=True, verbose_name='extraLight color')),
            ],
            options={
                'verbose_name': 'Hub Theme Color',
                'verbose_name_plural': 'Hub Theme Color',
            },
        ),
        migrations.RemoveField(
            model_name='hub',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='hubtheme',
            name='name',
        ),
        migrations.AddField(
            model_name='hubtheme',
            name='hub',
            field=models.OneToOneField(blank=True, help_text='The theme for the hub', max_length=1024, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hub_theme', to='hubs.hub', verbose_name='hub_theme'),
        ),
        migrations.AlterField(
            model_name='hubtheme',
            name='primary_color',
            field=models.ForeignKey(blank=True, help_text='primary_color', max_length=1024, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_color', to='hubs.hubthemecolor', verbose_name='primary_color'),
        ),
        migrations.AlterField(
            model_name='hubtheme',
            name='secondary_color',
            field=models.ForeignKey(blank=True, help_text='secondary_color', max_length=1024, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_color', to='hubs.hubthemecolor', verbose_name='secondary_color'),
        ),
    ]
