# Generated by Django 3.2.23 on 2024-11-25 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0023_auto_20241125_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubtheme',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='hubtheme',
            name='secondary_color',
        ),
        migrations.AddField(
            model_name='hubtheme',
            name='primary',
            field=models.ForeignKey(blank=True, help_text='primary_color', max_length=1024, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary', to='hubs.hubthemecolor', verbose_name='primary_color'),
        ),
        migrations.AddField(
            model_name='hubtheme',
            name='secondary',
            field=models.ForeignKey(blank=True, help_text='secondary_color', max_length=1024, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary', to='hubs.hubthemecolor', verbose_name='secondary_color'),
        ),
    ]
