# Generated by Django 3.2.23 on 2024-11-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0024_auto_20241125_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubtheme',
            name='hub_type',
            field=models.IntegerField(choices=[(0, 'light mode'), (1, 'dark mode')], default=0, help_text='theme mode', verbose_name='theme mode'),
        ),
    ]
