# Generated by Django 3.2.23 on 2024-11-27 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0026_rename_hub_type_hubtheme_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubtheme',
            name='text',
            field=models.ForeignKey(blank=True, help_text='Set the text color', max_length=1024, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text', to='hubs.hubthemecolor', verbose_name='text_color'),
        ),
    ]
