# Generated by Django 3.2.23 on 2024-11-27 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0027_hubtheme_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubtheme',
            name='mode',
        ),
    ]
