# Generated by Django 3.2.23 on 2024-12-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0028_remove_hubtheme_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubtheme',
            name='text',
        ),
        migrations.RemoveField(
            model_name='hubthemecolor',
            name='lightHover',
        ),
        migrations.AddField(
            model_name='hubthemecolor',
            name='contrastText',
            field=models.CharField(blank=True, help_text='contrastText color', max_length=200, null=True, verbose_name='contrastText color'),
        ),
    ]
