# Generated by Django 3.2.23 on 2024-12-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0029_auto_20241202_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubthemecolor',
            name='background_default',
            field=models.CharField(blank=True, help_text='default background color', max_length=1024, null=True, verbose_name='default background color'),
        ),
        migrations.AddField(
            model_name='hubthemecolor',
            name='background_paper',
            field=models.CharField(blank=True, help_text='paper background color', max_length=1024, null=True, verbose_name='paper background color'),
        ),
    ]
