# Generated by Django 5.1.2 on 2024-12-17 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hubs", "0031_auto_20241212_1206"),
    ]

    operations = [
        migrations.AddField(
            model_name="hubthemecolor",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Used to reference this color",
                max_length=200,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="hubtheme",
            name="background_default",
            field=models.ForeignKey(
                blank=True,
                help_text="Use hex code (e.g. #FFF)",
                max_length=1024,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="background_default",
                to="hubs.hubthemecolor",
                verbose_name="default background color",
            ),
        ),
        migrations.AlterField(
            model_name="hubtheme",
            name="hub",
            field=models.OneToOneField(
                blank=True,
                help_text="The hub for which the theme should be used",
                max_length=1024,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hub_theme",
                to="hubs.hub",
                verbose_name="Hub",
            ),
        ),
        migrations.AlterField(
            model_name="hubtheme",
            name="primary",
            field=models.ForeignKey(
                blank=True,
                help_text="Use hex code (e.g. #FFF)",
                max_length=1024,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primary",
                to="hubs.hubthemecolor",
                verbose_name="primary_color",
            ),
        ),
        migrations.AlterField(
            model_name="hubtheme",
            name="secondary",
            field=models.ForeignKey(
                blank=True,
                help_text="Use hex code (e.g. #FFF)",
                max_length=1024,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="secondary",
                to="hubs.hubthemecolor",
                verbose_name="secondary_color",
            ),
        ),
        migrations.AlterField(
            model_name="hubthemecolor",
            name="contrastText",
            field=models.CharField(
                blank=True,
                help_text="Color which has strong contrast to the main color. This color will be used for text and small elements if the main color is used for the background.",
                max_length=200,
                null=True,
                verbose_name="Contrast Text Color",
            ),
        ),
        migrations.AlterField(
            model_name="hubthemecolor",
            name="extraLight",
            field=models.CharField(
                blank=True,
                help_text="the extra light variation of the main color (use hex code, e.g. #FFF)",
                max_length=200,
                null=True,
                verbose_name="Extra Light Color",
            ),
        ),
        migrations.AlterField(
            model_name="hubthemecolor",
            name="light",
            field=models.CharField(
                blank=True,
                help_text="the lighter variation of the main color (use hex code, e.g. #FFF)",
                max_length=200,
                null=True,
                verbose_name="Light Color",
            ),
        ),
        migrations.AlterField(
            model_name="hubthemecolor",
            name="main",
            field=models.CharField(
                blank=True,
                help_text="main color (use hex code, e.g. #FFF)",
                max_length=200,
                null=True,
                verbose_name="Main Color",
            ),
        ),
    ]
