# Generated by Django 3.2.23 on 2024-12-18 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0031_auto_20241212_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubtheme',
            name='background_paper',
        ),
    ]
