# Generated by Django 5.1.2 on 2025-01-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hubs", "0032_hubthemecolor_name_alter_hubtheme_background_default_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hubtheme",
            name="background_paper",
        ),
    ]
