# Generated by Django 5.1.2 on 2024-12-20 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hubs", "0032_remove_hubtheme_background_paper"),
        ("hubs", "0033_remove_hubtheme_background_paper"),
    ]

    operations = []
