# Generated by Django 5.1.2 on 2025-02-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hubs", "0033_remove_hubtheme_background_paper"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hub",
            name="hub_type",
            field=models.IntegerField(
                choices=[(0, "sector hub"), (1, "location hub"), (2, "custom hub")],
                default=0,
                help_text="Type of hub",
                verbose_name="Hub Type",
            ),
        ),
    ]
