# Generated by Django 3.2.23 on 2025-01-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0034_merge_20241220_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubthemecolor',
            name='extraLight',
            field=models.CharField(blank=True, help_text='the extra light variation of the main color (use hex code, e.g. #FFF)', max_length=200, null=True, verbose_name='Extra Light Color'),
        ),
        migrations.AlterField(
            model_name='hubthemecolor',
            name='light',
            field=models.CharField(blank=True, help_text='the lighter variation of the main color (use hex code, e.g. #FFF)', max_length=200, null=True, verbose_name='Light Color'),
        ),
        migrations.AlterField(
            model_name='hubthemecolor',
            name='main',
            field=models.CharField(blank=True, help_text='main color (use hex code, e.g. #FFF)', max_length=200, null=True, verbose_name='Main Color'),
        ),
    ]
