# Generated by Django 3.2.25 on 2025-02-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0034_alter_hub_hub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='email_sender_name',
            field=models.CharField(blank=True, help_text='Name in which emails related to this hub should be sent (e.g. Climate Connect)', max_length=128, null=True, verbose_name='Email Sender Name'),
        ),
        migrations.AddField(
            model_name='hub',
            name='from_email',
            field=models.CharField(blank=True, help_text='Email address from which emails relating this hub are sent', max_length=128, null=True, verbose_name='From Email address (e.g. noreply@climateconnect.earth)'),
        ),
    ]
