# Generated by Django 3.2.23 on 2025-03-04 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0021_auto_20241113_0916'),
        ('hubs', '0035_auto_20250218_1128'),
    ]

    operations = [
    ]
