# Generated by Django 3.2.23 on 2025-05-13 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0036_hub_landing_page_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubtheme',
            name='header_background',
            field=models.ForeignKey(blank=True, help_text='Use hex code (e.g. #FFF)', max_length=1024, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='header_background', to='hubs.hubthemecolor', verbose_name='Header background color'),
        ),
    ]
