# Generated by Django 3.2.25 on 2025-06-24 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0036_hub_landing_page_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='parent_hub',
            field=models.ForeignKey(blank=True, help_text='Points to the parent hub if this is a sub hub', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_hubs', to='hubs.hub', verbose_name='Parent Hub'),
        ),
    ]
