# Generated by Django 3.2.25 on 2025-07-06 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0037_hub_parent_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='icon_background_color',
            field=models.CharField(blank=True, help_text='The background color of the icon as a hex code (e.g. #FFF or #002244).', max_length=7, null=True, verbose_name='Icon Background Color'),
        ),
        migrations.AlterField(
            model_name='hub',
            name='parent_hub',
            field=models.ForeignKey(blank=True, help_text='Points to the parent hub if this is a sub-hub', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_hubs', to='hubs.hub', verbose_name='Parent Hub'),
        ),
    ]
