# Generated by Django 3.2.25 on 2025-07-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0111_alter_sector_key'),
        ('hubs', '0039_auto_20250706_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='sectors',
            field=models.ManyToManyField(blank=True, help_text='Only projects with these sectors will be shown in the hub (applies only to hubs of type sector_hub)', related_name='hub_sectors', to='organization.Sector', verbose_name='Hub sectors'),
        ),
    ]
