# Generated by Django 3.2.25 on 2025-07-21 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0037_hubtheme_header_background'),
        ('hubs', '0040_alter_hub_sectors'),
    ]

    operations = [
    ]
