# Generated by Django 3.2.25 on 2025-08-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0041_merge_20250721_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='welcome_box_component',
            field=models.CharField(blank=True, help_text='Provide the welcome box component name. Please ensure it matches the component name from Webflow.', max_length=128, null=True, verbose_name='Welcome box component name'),
        ),
    ]
