# Generated by Django 3.2.25 on 2025-09-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0041_merge_20250721_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubambassador',
            name='custom_ambassador_box_text',
            field=models.CharField(blank=True, help_text='Custom text showing up in the box displaying the ambassador. Default: <First name> is responsible for the ClimateHub <Hubname> and is there for you.', max_length=1024, null=True, verbose_name='Custom box text'),
        ),
        migrations.AddField(
            model_name='hubambassador',
            name='custom_ambassador_box_text_de',
            field=models.CharField(blank=True, help_text='German translation for custom ambassador box text', max_length=1024, null=True, verbose_name='Custom box text'),
        ),
    ]
