# Generated by Django 3.2.25 on 2026-01-22 17:07

from django.db import migrations, models
import hubs.models.hub


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0042_auto_20250929_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubsupporter',
            name='image_only',
            field=models.BooleanField(default=False, help_text='If true, only the standalone_image will be shown without name. It will stretch through the whole supporters box', verbose_name='Image only'),
        ),
        migrations.AddField(
            model_name='hubsupporter',
            name='standalone_image',
            field=models.ImageField(blank=True, help_text='If image_only is set to true you can add a standalone image here that will stretch through the whole supporters box. Logo will just be used for the supporters preview on mobile', null=True, upload_to=hubs.models.hub.hub_supporter_standalone_image_path, verbose_name='Standalone Image'),
        ),
        migrations.AlterField(
            model_name='hubsupporter',
            name='logo',
            field=models.ImageField(blank=True, help_text='Supporter logo (Square)', null=True, upload_to=hubs.models.hub.hub_supporter_logo_path, verbose_name='Logo'),
        ),
    ]
