# Generated by Django 3.2.25 on 2025-08-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0042_hub_welcome_box_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='welcome_box_component',
            field=models.CharField(blank=True, help_text="Provide the welcome box component name. Please ensure it matches the component name from Webflow.The name must be identical for both the English and German versions, with the language code at the beginning (e.g. 'EnWelcomeBox' or 'DeWelcomeBox').", max_length=128, null=True, verbose_name='Welcome box component name'),
        ),
    ]
