# Generated by Django 3.2.25 on 2026-01-26 16:12

from django.db import migrations, models
import hubs.models.hub


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0043_auto_20260122_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubsupporter',
            name='image_only',
        ),
        migrations.AlterField(
            model_name='hubsupporter',
            name='standalone_image',
            field=models.ImageField(blank=True, help_text='If you add a standalone image, it will be shown stretching through the whole supporters box. Logo will just be used for the supporters preview on mobile', null=True, upload_to=hubs.models.hub.hub_supporter_standalone_image_path, verbose_name='Standalone Image'),
        ),
    ]
