# Generated by Django 4.2.27 on 2026-03-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hubs", "0044_auto_20260126_1612"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hub",
            name="welcome_message_logged_in",
            field=models.CharField(
                blank=True,
                help_text='Displayed on the dashboard on location hubs when logged in. First name can be personalised using ${user.first_name}."',
                max_length=2048,
                null=True,
                verbose_name="Welcome message (logged in)",
            ),
        ),
        migrations.AlterField(
            model_name="hubtranslation",
            name="welcome_message_logged_in_translation",
            field=models.CharField(
                blank=True,
                help_text='Displayed on the dashboard on location hubs when logged in. First name can be personalised using ${user.first_name}."',
                max_length=2048,
                null=True,
                verbose_name="Translation of welcome message (logged in)",
            ),
        ),
    ]
