import React, { useContext } from "react";
import UserContext from "../src/components/context/UserContext";
import ImprintEnglish from "../src/components/legal/imprint/ImprintEnglish";
import ImprintGerman from "../src/components/legal/imprint/ImprintGerman";

/*NOTE(Christoph) 
The impressum is auto-generated by the online-law platform e-recht24.de.
It's legally required for german websites and shows who is responsible for the content.
Until we have incorporated a charitable company, I put my name as the responsible entity.
*/
export default function Imprint() {
  const { locale } = useContext(UserContext);
  if (locale === "en") return <ImprintEnglish />;
  if (locale === "de") return <ImprintGerman />;
}
