# Generated by Django 4.2.27 on 2026-03-03 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureToggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique name for the feature toggle (e.g., 'NEW_DASHBOARD')", max_length=128, unique=True, validators=[django.core.validators.RegexValidator(message='Name must contain only uppercase letters, numbers, and underscores', regex='^[A-Z0-9_]+$')], verbose_name='Toggle Name')),
                ('description', models.TextField(blank=True, default='', help_text='Description of what this feature toggle controls', verbose_name='Description')),
                ('production_is_active', models.BooleanField(default=False, help_text='Whether the feature is active in production', verbose_name='Production Active')),
                ('staging_is_active', models.BooleanField(default=False, help_text='Whether the feature is active in staging', verbose_name='Staging Active')),
                ('development_is_active', models.BooleanField(default=False, help_text='Whether the feature is active in development', verbose_name='Development Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when the feature toggle was created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time when the feature toggle was last updated', verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Feature Toggle',
                'verbose_name_plural': 'Feature Toggles',
                'ordering': ['name'],
            },
        ),
    ]
