# Generated by Django 4.2.27 on 2026-03-18 13:17

from django.db import migrations


def create_event_registration_toggle(apps, schema_editor):
    FeatureToggle = apps.get_model("feature_toggles", "FeatureToggle")
    FeatureToggle.objects.get_or_create(
        name="EVENT_REGISTRATION",
        defaults={
            "description": (
                "Enables the event registration feature, allowing event-type projects "
                "to configure max_participants and a registration_end_date."
            ),
            "production_is_active": False,
            "staging_is_active": True,
            "development_is_active": True,
        },
    )


def remove_event_registration_toggle(apps, schema_editor):
    FeatureToggle = apps.get_model("feature_toggles", "FeatureToggle")
    FeatureToggle.objects.filter(name="EVENT_REGISTRATION").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("feature_toggles", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_event_registration_toggle,
            reverse_code=remove_event_registration_toggle,
        ),
    ]
