# Generated by Django 4.2.27 on 2026-04-20 12:00

from django.db import migrations


def create_auth_unification_toggle(apps, schema_editor):
    FeatureToggle = apps.get_model("feature_toggles", "FeatureToggle")
    FeatureToggle.objects.get_or_create(
        name="AUTH_UNIFICATION",
        defaults={
            "description": (
                "Enables the unified authentication system. When active, /signin and "
                "/signup redirect to the new /login page, consolidating the authentication "
                "experience into a single, unified flow."
            ),
            "production_is_active": False,
            "staging_is_active": False,
            "development_is_active": False,
        },
    )


def remove_auth_unification_toggle(apps, schema_editor):
    FeatureToggle = apps.get_model("feature_toggles", "FeatureToggle")
    FeatureToggle.objects.filter(name="AUTH_UNIFICATION").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("feature_toggles", "0002_add_event_registration_toggle"),
    ]

    operations = [
        migrations.RunPython(
            create_auth_unification_toggle,
            reverse_code=remove_auth_unification_toggle,
        ),
    ]
