# Generated by Django 4.2.27 on 2026-05-11

from django.db import migrations


def create_registration_custom_fields_toggle(apps, schema_editor):
    FeatureToggle = apps.get_model("feature_toggles", "FeatureToggle")
    FeatureToggle.objects.get_or_create(
        name="REGISTRATION_CUSTOM_FIELDS",
        defaults={
            "description": (
                "Enables the custom registration fields UI for event organisers. "
                "When active, organisers can add up to 5 custom fields (checkbox, "
                "option select) to an event's registration form. All Phase 4a tasks "
                "must be validated on staging simultaneously before flipping this to "
                "production."
            ),
            "production_is_active": False,
            "staging_is_active": True,
            "development_is_active": True,
        },
    )


def remove_registration_custom_fields_toggle(apps, schema_editor):
    FeatureToggle = apps.get_model("feature_toggles", "FeatureToggle")
    FeatureToggle.objects.filter(name="REGISTRATION_CUSTOM_FIELDS").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("feature_toggles", "0003_add_auth_unification_toggle"),
    ]

    operations = [
        migrations.RunPython(
            create_registration_custom_fields_toggle,
            reverse_code=remove_registration_custom_fields_toggle,
        ),
    ]
