# Generated by Django 4.2.27 on 2026-07-07

from django.db import migrations


def create_event_calendar_toggle(apps, schema_editor):
    FeatureToggle = apps.get_model("feature_toggles", "FeatureToggle")
    FeatureToggle.objects.get_or_create(
        name="EVENT_CALENDAR_FEATURE",
        defaults={
            "description": (
                "Enables the Event Calendar page (POC). The page lists events "
                "chronologically in a dedicated route, gated only in the frontend. "
                "Keep production disabled until the POC is validated on staging."
            ),
            "production_is_active": False,
            "staging_is_active": True,
            "development_is_active": True,
        },
    )


def remove_event_calendar_toggle(apps, schema_editor):
    FeatureToggle = apps.get_model("feature_toggles", "FeatureToggle")
    FeatureToggle.objects.filter(name="EVENT_CALENDAR_FEATURE").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("feature_toggles", "0004_add_registration_custom_fields_toggle"),
    ]

    operations = [
        migrations.RunPython(
            create_event_calendar_toggle,
            reverse_code=remove_event_calendar_toggle,
        ),
    ]
