# Generated by Django 4.2.27 on 2026-08-04

from django.db import migrations


def create_locationiq_autocomplete_toggle(apps, schema_editor):
    FeatureToggle = apps.get_model("feature_toggles", "FeatureToggle")
    FeatureToggle.objects.get_or_create(
        name="LOCATIONIQ_AUTOCOMPLETE",
        defaults={
            "description": (
                "Routes location autocomplete through the backend proxy "
                "(/api/location_autocomplete/): Redis result cache, Celery "
                "lookup queue, LocationIQ with a Nominatim fallback. When "
                "disabled, the frontend calls nominatim.openstreetmap.org "
                "directly from the browser as it did before the POC, and the "
                "backend never calls LocationIQ. Keep production disabled "
                "until the POC is validated on staging."
            ),
            "production_is_active": False,
            "staging_is_active": True,
            "development_is_active": True,
        },
    )


def remove_locationiq_autocomplete_toggle(apps, schema_editor):
    FeatureToggle = apps.get_model("feature_toggles", "FeatureToggle")
    FeatureToggle.objects.filter(name="LOCATIONIQ_AUTOCOMPLETE").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("feature_toggles", "0005_add_event_calendar_toggle"),
    ]

    operations = [
        migrations.RunPython(
            create_locationiq_autocomplete_toggle,
            reverse_code=remove_locationiq_autocomplete_toggle,
        ),
    ]
