# Generated by Django 2.2.13 on 2021-01-15 06:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text="Points to location's city name", max_length=1024, verbose_name='Name')),
                ('state', models.CharField(help_text="Points to location's state name", max_length=1024, verbose_name='Name')),
                ('country', models.CharField(help_text="Points to location's country name", max_length=1024, verbose_name='Name')),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326)),
            ],
        ),
    ]
