# Generated by Django 2.2.13 on 2021-01-25 09:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={"verbose_name": "Location", "verbose_name_plural": "Location"},
        ),
    ]
