# Generated by Django 2.2.13 on 2021-01-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='osm_id',
            field=models.PositiveIntegerField(default=1, help_text='The internal id of this location openstreetmaps', verbose_name='OSM ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='place_id',
            field=models.PositiveIntegerField(default=3, help_text="Nominatim's place id of this location", verbose_name='Place ID'),
            preserve_default=False,
        ),
    ]
