# Generated by Django 2.2.13 on 2021-01-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20210121_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default=1, help_text='Points to the (shortened) name of the location', max_length=4096, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
