# Generated by Django 2.2.13 on 2021-02-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0006_auto_20210218_0859"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="is_formatted",
            field=models.BooleanField(
                default=False,
                help_text="helper column after migration inserted wrong languages and location shapes",
                verbose_name="Is Formatted?",
            ),
        ),
    ]
