# Generated by Django 2.2.18 on 2021-04-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_location_is_formatted'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city_de_translation',
            field=models.CharField(blank=True, help_text='Deutsch translation for city column', max_length=1024, null=True, verbose_name='City DE translation'),
        ),
        migrations.AddField(
            model_name='location',
            name='country_de_translation',
            field=models.CharField(blank=True, help_text='Deutsch translation for country column', max_length=1024, null=True, verbose_name='Country DE translation'),
        ),
        migrations.AddField(
            model_name='location',
            name='name_de_translation',
            field=models.CharField(blank=True, help_text='Deutsch translation of location name', max_length=4096, null=True, verbose_name='Name DE translation'),
        ),
        migrations.AddField(
            model_name='location',
            name='state_de_translation',
            field=models.CharField(blank=True, help_text='Deutsch translation for state column', max_length=1024, null=True, verbose_name='State DE translation'),
        ),
    ]
