# Generated by Django 3.2 on 2022-04-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0008_locationtranslation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="locationtranslation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
