# Generated by Django 3.2.18 on 2023-07-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_auto_20220419_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='exact_address',
            field=models.CharField(blank=True, help_text="Points to the exact address the location is on (e.g. 'Silk Road 50')", max_length=1024, null=True, verbose_name='Road'),
        ),
        migrations.AddField(
            model_name='location',
            name='place_name',
            field=models.CharField(blank=True, help_text='If it is a specific place (e.g. city hall) this contains the name of the place', max_length=1024, null=True, verbose_name='Place Name'),
        ),
    ]
