# Generated by Django 3.2.25 on 2025-10-14 13:45
from django.db import migrations, models
from pathlib import Path
import csv


CURRENT_DIR = Path(__file__).resolve()
LOOKUP_DIR = CURRENT_DIR.parent.parent.parent

LOOKUP_FILE = str(LOOKUP_DIR / "climateconnect_api" / "management" / "commands" / "osm_type_lookup_tables" / "lookup.csv")
LOOKUP_OSM_ID_FILE = str(LOOKUP_DIR / "climateconnect_api" / "management" / "commands" / "osm_type_lookup_tables" / "osm_id_lookup.csv")

def safe_int_conversion(string_value):
    if string_value is None:
        return None
    string_value = string_value.strip() #remove spaces, tabs, ...
    if not string_value:
        return None
    try:
        return int(string_value)
    except Exception as e:
        print(f"WARNING: '{string_value}' could not be converted to int")
        return None
    

def open_csv(file_path: str) -> list[dict]:
    rows = []
    try:
        with open(file_path, mode="r", newline="", encoding="utf-8") as file:
            # csv.DictReader maps the header row to keys in a dictionary for each data row
            reader = csv.DictReader(file)
            if reader.fieldnames:  # clean fieldnames from invisible strings
                cleaned_fieldnames = [
                    name.strip().replace('"', "").replace("\ufeff", "")
                    for name in reader.fieldnames
                ]
                reader.fieldnames = cleaned_fieldnames
            for row in reader:
                rows.append(row)
    except FileNotFoundError:
        raise FileNotFoundError(f"Required migration data file '{file_path}' was not found.")
    return rows


def fill_osm_type(apps, schema_editor, lookup_file: str = LOOKUP_FILE, lookup_osm_id_file: str = LOOKUP_OSM_ID_FILE):
    Location = apps.get_model("location", "Location")
    lookup_path = Path(lookup_file)
    if not lookup_path.exists():
        raise RuntimeError(f"Error: lookup_file not found at path {lookup_path}")

    #normal lookup
    lookup_data = open_csv(lookup_path)
    updated_count = 0
    for line in lookup_data:
            osm_id = safe_int_conversion(line['osm_id'])
            if osm_id is None: 
                continue
            updated_count += Location.objects.filter(
                osm_id=osm_id
            ).update(
                osm_type=line['osm_type']
            )
    print(f"Updated {updated_count} locations with respective osm_type")
    
    
    #lookup for locations without osm_ids or invalid osm_ids
    lookup_osm_id_path = Path(lookup_osm_id_file)
    if not lookup_osm_id_path.exists():
        print(f"Error: lookup_osm_id_file not found at path {lookup_osm_id_path}")
        return

    osm_lookup_data = open_csv(lookup_osm_id_path)
    updated_count = 0
    for line in osm_lookup_data:
        place_id = safe_int_conversion(line['place_id'])
        new_osm_id = safe_int_conversion(line['osm_id'])
        if place_id is None:
            continue
        updated_count += Location.objects.filter(
            place_id=place_id
        ).update(
            osm_id=new_osm_id,
            osm_type=line['osm_type']
        )
        
        
    print(f"Updated {updated_count} locations with respective osm_id and osm_type")

  
    


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0012_add_osm_type_to_locatios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='osm_type',
            field=models.CharField(blank=True, help_text='The internal type of this location openstreetmaps', max_length=1, null=True, verbose_name='OSM TYPE'),
        ),
        migrations.RunPython(
            fill_osm_type,
            reverse_code=migrations.RunPython.noop,
        ),
    ]

