# Generated by Django 3.2.25 on 2025-10-14 13:45
from django.db import migrations, models
from pathlib import Path
import csv

LOOKUP_FILE = '../../climateconnect_api/management/commands/osm_type_lookup_tables/lookup.csv'
LOOKUP_OSM_ID_FILE = '../../climateconnect_api/management/commands/osm_type_lookup_tables/osm_id_lookup.csv'

def safe_int_migration(str):
    if str is None:
        return None
    str = str.strip() #remove spaces, tabs, ...
    if not str:
        return None
    try:
        return int(str)
    except Exception as e:
        print(f"WARNING: '{str}' could not be converted to int")
        return None


def fill_osm_type(apps, schema_editor, lookup_file: str = LOOKUP_FILE, lookup_osm_id_file: str = LOOKUP_OSM_ID_FILE):
    Location = apps.get_model("location", "Location")
    lookup_path = Path(lookup_file)
    if not lookup_path.exists():
        print(f"Error: lookup_file not found at path {lookup_path}")
        return {}

    #normal lookup
    try:
        with open(lookup_path, mode='r', encoding='utf-8') as file:
            reader = csv.DictReader(file)
            updated_count = 0
            for line in reader:
                osm_id = safe_int_migration(line['osm_id'])
                if osm_id is None: 
                    continue
                updated_count += Location.objects.filter(
                    osm_id=osm_id
                ).update(
                    osm_type=line['osm_type']
                )
            print(f"Updated {updated_count} locations with respective osm_type")
    except Exception as e:
        print(f"Error: {e}")
    
    #lookup for locations without osm_ids
    lookup_osm_id_path = Path(lookup_osm_id_file)
    if not lookup_osm_id_path.exists():
        print(f"Error: lookup_file not found at path {lookup_path}")
        return {}

    try:
        with open(lookup_osm_id_path, mode='r', encoding='utf-8') as file:
            reader = csv.DictReader(file)
            updated_count = 0
            for line in reader:
                place_id = safe_int_migration(line['place_id'])
                new_osm_id = safe_int_migration(line['osm_id'])
                if place_id is None:
                    continue
                updated_count += Location.objects.filter(
                    place_id=place_id
                ).update(
                    osm_id=new_osm_id,
                    osm_type=line['osm_type']
                )
            print(f"Updated {updated_count} locations with respective osm_id and osm_type")
    except Exception as e:
        print(f"Error: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0012_add_osm_type_to_locatios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='osm_type',
            field=models.CharField(blank=True, help_text='The internal type of this location openstreetmaps', max_length=1, null=True, verbose_name='OSM TYPE'),
        ),
        migrations.RunPython(
            fill_osm_type,
            reverse_code=migrations.RunPython.noop,
        ),
    ]

