# Generated by Django 3.2.25 on 2025-12-04 14:52

import csv
from pathlib import Path
from django.db import migrations, models
CURRENT_DIR = Path(__file__).resolve()
LOOKUP_DIR = CURRENT_DIR.parent.parent.parent

LOOKUP_OSM_CLASS_FILE = str(LOOKUP_DIR / "climateconnect_api" / "management" / "commands" / "osm_lookup_tables" / "osm_class_lookup.csv")

def safe_int_conversion(string_value):
    if string_value is None:
        return None
    string_value = string_value.strip() #remove spaces, tabs, ...
    if not string_value:
        return None
    try:
        return int(string_value)
    except Exception as e:
        print(f"WARNING: '{string_value}' could not be converted to int")
        return None

def open_csv(file_path: str) -> list[dict]:
    rows = []
    try:
        with open(file_path, mode="r", newline="", encoding="utf-8") as file:
            # csv.DictReader maps the header row to keys in a dictionary for each data row
            reader = csv.DictReader(file)
            if reader.fieldnames:  # clean fieldnames from invisible strings
                cleaned_fieldnames = [
                    name.strip().replace('"', "").replace("\ufeff", "")
                    for name in reader.fieldnames
                ]
                reader.fieldnames = cleaned_fieldnames
            for row in reader:
                rows.append(row)
    except FileNotFoundError:
        raise FileNotFoundError(f"Required migration data file '{file_path}' was not found.")
    return rows


def fill_class_type_display_name(apps, schema_editor, lookup_osm_class_file: str = LOOKUP_OSM_CLASS_FILE):
    Location = apps.get_model("location", "Location")
    lookup_path = Path(lookup_osm_class_file)
    if not lookup_path.exists():
        raise RuntimeError(f"Error: lookup_file not found at path {lookup_path}")

    #normal lookup
    lookup_data = open_csv(lookup_path)
    updated_count = 0
    for line in lookup_data:
            osm_id = safe_int_conversion(line['osm_id'])
            osm_type = str(line['osm_type'])
            if osm_id is None: 
                continue
            updated_count += Location.objects.filter(
                osm_id=osm_id,
                osm_type=osm_type
            ).update(
                osm_class=line['osm_class'],
                osm_class_type=line['osm_class_type'],
                display_name=line['display_name']
            )
    print(f"Updated {updated_count} locations with respective osm_class, osm_class_type and display_name.")



class Migration(migrations.Migration):

    dependencies = [
        ('location', '0013_alter_location_osm_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='display_name',
            field=models.CharField(blank=True, help_text="Nominatim's full display name of the location", max_length=1024, null=True, verbose_name='Display Name'),
        ),
        migrations.AddField(
            model_name='location',
            name='osm_class',
            field=models.CharField(blank=True, help_text='The internal class of this location in openstreetmaps', max_length=100, null=True, verbose_name='OSM CLASS'),
        ),
        migrations.AddField(
            model_name='location',
            name='osm_class_type',
            field=models.CharField(blank=True, help_text='The internal type specifying the osm_class of this location in openstreetmaps', max_length=100, null=True, verbose_name='OSM CLASS TYPE'),
        ),
        migrations.AlterField(
            model_name='location',
            name='osm_type',
            field=models.CharField(blank=True, choices=[('N', 'node'), ('W', 'way'), ('R', 'relation')], help_text='The internal type of this location openstreetmaps', max_length=1, null=True, verbose_name='OSM TYPE'),
        ),
        migrations.RunPython(
            fill_class_type_display_name,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
