# Generated by Django 3.2.25 on 2026-01-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0015_fill_missing_osm_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='osm_class',
            field=models.CharField(blank=True, help_text='The internal class of this location in openstreetmaps', max_length=100, null=True, verbose_name='Osm Class'),
        ),
        migrations.AlterField(
            model_name='location',
            name='osm_class_type',
            field=models.CharField(blank=True, help_text='The internal type specifying the osm_class of this location in openstreetmaps', max_length=100, null=True, verbose_name='Osm Class Type'),
        ),
        migrations.AlterField(
            model_name='location',
            name='osm_id',
            field=models.BigIntegerField(blank=True, help_text='The internal id of this location openstreetmaps', null=True, verbose_name='Osm ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='osm_type',
            field=models.CharField(blank=True, choices=[('N', 'node'), ('W', 'way'), ('R', 'relation')], help_text='The internal type of this location openstreetmaps', max_length=1, null=True, verbose_name='Osm Type'),
        ),
    ]
