# Generated by Django 3.2.25 on 2026-03-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0016_auto_20260122_1706"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["osm_id", "osm_type", "osm_class"],
                name="location_loc_osm_id_b7b8a5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["place_id"], name="location_place_id_idx"),
        ),
    ]
