# Generated by Django 4.2.30 on 2026-06-18 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0019_nominatim_stats"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nominatimrequestlog",
            name="bucket_key",
        ),
        migrations.RemoveField(
            model_name="nominatimrequestlog",
            name="count",
        ),
        migrations.RemoveField(
            model_name="nominatimrequestlog",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="nominatimrequestlog",
            name="processed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="nominatimperiodstats",
            name="peak_req_per_second",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Maximum number of requests that arrived in the same second",
            ),
        ),
        migrations.AlterField(
            model_name="nominatimrequestlog",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AddField(
            model_name="nominatimrequestlog",
            name="minute_key",
            field=models.BigIntegerField(
                db_index=True,
                default=0,
                help_text="Epoch minutes (epoch_seconds // 60) for grouping",
            ),
            preserve_default=False,
        ),
    ]
