# Generated by Django 4.2.30 on 2026-06-18 13:11

from django.db import migrations, models
import django.utils.timezone


def mark_existing_rows_processed(apps, schema_editor):
    """Mark all pre-existing NominatimRequestLog rows as processed so the
    aggregation task doesn't misinterpret old per-minute bucket rows (which
    each represented N requests) as single-request rows."""
    NominatimRequestLog = apps.get_model("location", "NominatimRequestLog")
    NominatimRequestLog.objects.filter(processed=False).update(processed=True)


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0019_nominatim_stats"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nominatimrequestlog",
            name="bucket_key",
        ),
        migrations.RemoveField(
            model_name="nominatimrequestlog",
            name="count",
        ),
        migrations.RemoveField(
            model_name="nominatimrequestlog",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="nominatimrequestlog",
            name="processed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(
            mark_existing_rows_processed,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="nominatimperiodstats",
            name="peak_req_per_second",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Maximum number of requests that arrived in the same second",
            ),
        ),
        migrations.AlterField(
            model_name="nominatimrequestlog",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AddField(
            model_name="nominatimrequestlog",
            name="minute_key",
            field=models.BigIntegerField(
                db_index=True,
                default=0,
                help_text="Epoch minutes (epoch_seconds // 60) for grouping",
            ),
            preserve_default=False,
        ),
    ]
