# Generated by Django 4.2.30 on 2026-08-20 12:29

from django.db import migrations


class Migration(migrations.Migration):
    """
    Both tracking models cover LocationIQ as well as Nominatim since 0021 added
    the `provider` column, so the "Nominatim" in their names is now wrong.

    RenameModel renames the tables in place (location_nominatimrequestlog ->
    location_autocompleterequestlog, same for the stats table); no rows are
    copied or dropped, and the `provider` values themselves are untouched —
    "nominatim" is still a real provider name.
    """

    dependencies = [
        ("location", "0021_add_provider_field_to_tracking_models"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NominatimPeriodStats",
            new_name="AutocompletePeriodStats",
        ),
        migrations.RenameModel(
            old_name="NominatimRequestLog",
            new_name="AutocompleteRequestLog",
        ),
        migrations.AlterModelOptions(
            name="autocompleteperiodstats",
            options={
                "verbose_name": "autocomplete period stats",
                "verbose_name_plural": "autocomplete period stats",
            },
        ),
        migrations.AlterModelOptions(
            name="autocompleterequestlog",
            options={
                "verbose_name": "autocomplete request log",
                "verbose_name_plural": "autocomplete request logs",
            },
        ),
        migrations.RenameIndex(
            model_name="autocompleteperiodstats",
            new_name="location_au_period__60e34f_idx",
            old_name="location_no_period__5a9ac2_idx",
        ),
    ]
