name: Python linting with flake8
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          # Note: be aware of specific Python versions. This version should always
          # match what version we specif in our other setup files, like start_backend.sh.
          # 3.6.9 started breaking GitHub actions, see related issue:
          # https://github.com/actions/setup-python/issues/162#issuecomment-1324176396
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 backend --count --select=E9,F6,F7,F8 --show-source --statistics
