name: Python Linting
on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 backend --count --select=F8,E9,F6,F7,F8 --show-source --statistics
          #flake8 backend --count --max-complexity=10 --max-line-length=300 --statistics
