# Generated by Django 2.2.18 on 2021-05-09 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ideas", "0009_idea_thumbnail_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="idea",
            old_name="summary",
            new_name="short_description",
        ),
        migrations.RemoveField(
            model_name="idea",
            name="description",
        ),
    ]
