# Generated by Django 2.2.18 on 2021-05-09 18:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ideas", "0010_auto_20210509_1737"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ideatranslation",
            old_name="name",
            new_name="name_translation",
        ),
        migrations.RenameField(
            model_name="ideatranslation",
            old_name="summary",
            new_name="short_description_translation",
        ),
        migrations.RemoveField(
            model_name="ideatranslation",
            name="description",
        ),
    ]
