# Generated by Django 2.2.18 on 2021-05-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0011_auto_20210509_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='url_slug',
            field=models.CharField(blank=True, help_text='URL slug for an idea', max_length=1024, null=True, verbose_name='URL Slug'),
        ),
    ]
